/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './rotas/__root';
import { Route as IndexRouteImport } from './rotas/index';
import { Route as AssinaturasRouteImport } from './rotas/assinaturas';
import { Route as AuditoriaRouteImport } from './rotas/auditoria';
import { Route as ConfiguracoesRouteImport } from './rotas/configuracoes';
import { Route as FilasRouteImport } from './rotas/filas';
import { Route as MetricasRouteImport } from './rotas/metricas';
import { Route as MonyRouteImport } from './rotas/mony';
import { Route as NovidadesRouteImport } from './rotas/novidades';
import { Route as PlanosRouteImport } from './rotas/planos';
import { Route as UsuariosRouteImport } from './rotas/usuarios';

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const AssinaturasRoute = AssinaturasRouteImport.update({
  id: '/assinaturas',
  path: '/assinaturas',
  getParentRoute: () => rootRouteImport,
} as any);
const AuditoriaRoute = AuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => rootRouteImport,
} as any);
const ConfiguracoesRoute = ConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => rootRouteImport,
} as any);
const FilasRoute = FilasRouteImport.update({
  id: '/filas',
  path: '/filas',
  getParentRoute: () => rootRouteImport,
} as any);
const MetricasRoute = MetricasRouteImport.update({
  id: '/metricas',
  path: '/metricas',
  getParentRoute: () => rootRouteImport,
} as any);
const MonyRoute = MonyRouteImport.update({
  id: '/mony',
  path: '/mony',
  getParentRoute: () => rootRouteImport,
} as any);
const NovidadesRoute = NovidadesRouteImport.update({
  id: '/novidades',
  path: '/novidades',
  getParentRoute: () => rootRouteImport,
} as any);
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any);
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/assinaturas': typeof AssinaturasRoute;
  '/auditoria': typeof AuditoriaRoute;
  '/configuracoes': typeof ConfiguracoesRoute;
  '/filas': typeof FilasRoute;
  '/metricas': typeof MetricasRoute;
  '/mony': typeof MonyRoute;
  '/novidades': typeof NovidadesRoute;
  '/planos': typeof PlanosRoute;
  '/usuarios': typeof UsuariosRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/assinaturas': typeof AssinaturasRoute;
  '/auditoria': typeof AuditoriaRoute;
  '/configuracoes': typeof ConfiguracoesRoute;
  '/filas': typeof FilasRoute;
  '/metricas': typeof MetricasRoute;
  '/mony': typeof MonyRoute;
  '/novidades': typeof NovidadesRoute;
  '/planos': typeof PlanosRoute;
  '/usuarios': typeof UsuariosRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/assinaturas': typeof AssinaturasRoute;
  '/auditoria': typeof AuditoriaRoute;
  '/configuracoes': typeof ConfiguracoesRoute;
  '/filas': typeof FilasRoute;
  '/metricas': typeof MetricasRoute;
  '/mony': typeof MonyRoute;
  '/novidades': typeof NovidadesRoute;
  '/planos': typeof PlanosRoute;
  '/usuarios': typeof UsuariosRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/assinaturas'
    | '/auditoria'
    | '/configuracoes'
    | '/filas'
    | '/metricas'
    | '/mony'
    | '/novidades'
    | '/planos'
    | '/usuarios';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/assinaturas'
    | '/auditoria'
    | '/configuracoes'
    | '/filas'
    | '/metricas'
    | '/mony'
    | '/novidades'
    | '/planos'
    | '/usuarios';
  id:
    | '__root__'
    | '/'
    | '/assinaturas'
    | '/auditoria'
    | '/configuracoes'
    | '/filas'
    | '/metricas'
    | '/mony'
    | '/novidades'
    | '/planos'
    | '/usuarios';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AssinaturasRoute: typeof AssinaturasRoute;
  AuditoriaRoute: typeof AuditoriaRoute;
  ConfiguracoesRoute: typeof ConfiguracoesRoute;
  FilasRoute: typeof FilasRoute;
  MetricasRoute: typeof MetricasRoute;
  MonyRoute: typeof MonyRoute;
  NovidadesRoute: typeof NovidadesRoute;
  PlanosRoute: typeof PlanosRoute;
  UsuariosRoute: typeof UsuariosRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/assinaturas': {
      id: '/assinaturas';
      path: '/assinaturas';
      fullPath: '/assinaturas';
      preLoaderRoute: typeof AssinaturasRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/auditoria': {
      id: '/auditoria';
      path: '/auditoria';
      fullPath: '/auditoria';
      preLoaderRoute: typeof AuditoriaRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/configuracoes': {
      id: '/configuracoes';
      path: '/configuracoes';
      fullPath: '/configuracoes';
      preLoaderRoute: typeof ConfiguracoesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/filas': {
      id: '/filas';
      path: '/filas';
      fullPath: '/filas';
      preLoaderRoute: typeof FilasRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/metricas': {
      id: '/metricas';
      path: '/metricas';
      fullPath: '/metricas';
      preLoaderRoute: typeof MetricasRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/mony': {
      id: '/mony';
      path: '/mony';
      fullPath: '/mony';
      preLoaderRoute: typeof MonyRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/novidades': {
      id: '/novidades';
      path: '/novidades';
      fullPath: '/novidades';
      preLoaderRoute: typeof NovidadesRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/planos': {
      id: '/planos';
      path: '/planos';
      fullPath: '/planos';
      preLoaderRoute: typeof PlanosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/usuarios': {
      id: '/usuarios';
      path: '/usuarios';
      fullPath: '/usuarios';
      preLoaderRoute: typeof UsuariosRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinaturasRoute: AssinaturasRoute,
  AuditoriaRoute: AuditoriaRoute,
  ConfiguracoesRoute: ConfiguracoesRoute,
  FilasRoute: FilasRoute,
  MetricasRoute: MetricasRoute,
  MonyRoute: MonyRoute,
  NovidadesRoute: NovidadesRoute,
  PlanosRoute: PlanosRoute,
  UsuariosRoute: UsuariosRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
