/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AtualizacaoCategoriaDto,
  CategoriaDto,
  ExcluirCategoriasParams,
  ListaCategoriasDto,
  ListarCategoriasParams,
  NovaCategoriaDto,
} from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListarCategoriasUrl = (params?: ListarCategoriasParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/categorias?${stringifiedParams}` : `/v1/categorias`;
};

export const listarCategorias = async (
  params?: ListarCategoriasParams,
  options?: Parameters<typeof requisicao>[1],
): Promise<ListaCategoriasDto> => {
  return requisicao<ListaCategoriasDto>(getListarCategoriasUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getListarCategoriasQueryKey = (params?: ListarCategoriasParams) => {
  return [`/v1/categorias`, ...(params ? [params] : [])] as const;
};

export const getListarCategoriasQueryOptions = <
  TData = Awaited<ReturnType<typeof listarCategorias>>,
  TError = unknown,
>(
  params?: ListarCategoriasParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCategorias>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListarCategoriasQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listarCategorias>>> = ({ signal }) =>
    listarCategorias(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listarCategorias>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListarCategoriasQueryResult = NonNullable<Awaited<ReturnType<typeof listarCategorias>>>;
export type ListarCategoriasQueryError = unknown;

export function useListarCategorias<
  TData = Awaited<ReturnType<typeof listarCategorias>>,
  TError = unknown,
>(
  params: undefined | ListarCategoriasParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCategorias>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarCategorias>>,
          TError,
          Awaited<ReturnType<typeof listarCategorias>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarCategorias<
  TData = Awaited<ReturnType<typeof listarCategorias>>,
  TError = unknown,
>(
  params?: ListarCategoriasParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCategorias>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarCategorias>>,
          TError,
          Awaited<ReturnType<typeof listarCategorias>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarCategorias<
  TData = Awaited<ReturnType<typeof listarCategorias>>,
  TError = unknown,
>(
  params?: ListarCategoriasParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCategorias>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListarCategorias<
  TData = Awaited<ReturnType<typeof listarCategorias>>,
  TError = unknown,
>(
  params?: ListarCategoriasParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCategorias>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListarCategoriasQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getCriarCategoriasUrl = () => {
  return `/v1/categorias`;
};

export const criarCategorias = async (
  novaCategoriaDto: NovaCategoriaDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<CategoriaDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<CategoriaDto>(getCriarCategoriasUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(novaCategoriaDto),
  });
};

export const getCriarCategoriasMutationKey = () => ['criarCategorias'] as const;

export const getCriarCategoriasMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarCategorias>>,
    TError,
    CriarCategoriasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarCategorias>>,
  TError,
  CriarCategoriasMutationVariables,
  TContext
> => {
  const mutationKey = getCriarCategoriasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarCategorias>>,
    CriarCategoriasMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return criarCategorias(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarCategoriasMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarCategorias>>
>;
export type CriarCategoriasMutationBody = NovaCategoriaDto;
export type CriarCategoriasMutationError = unknown;
export type CriarCategoriasMutationVariables = { data: NovaCategoriaDto };

export const useCriarCategorias = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarCategorias>>,
      TError,
      CriarCategoriasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarCategorias>>,
  TError,
  CriarCategoriasMutationVariables,
  TContext
> => {
  return useMutation(getCriarCategoriasMutationOptions(options), queryClient);
};
export const getAtualizarCategoriasUrl = (id: string) => {
  return `/v1/categorias/${id}`;
};

export const atualizarCategorias = async (
  id: string,
  atualizacaoCategoriaDto: AtualizacaoCategoriaDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<CategoriaDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<CategoriaDto>(getAtualizarCategoriasUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizacaoCategoriaDto),
  });
};

export const getAtualizarCategoriasMutationKey = () => ['atualizarCategorias'] as const;

export const getAtualizarCategoriasMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarCategorias>>,
    TError,
    AtualizarCategoriasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarCategorias>>,
  TError,
  AtualizarCategoriasMutationVariables,
  TContext
> => {
  const mutationKey = getAtualizarCategoriasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarCategorias>>,
    AtualizarCategoriasMutationVariables
  > = (props) => {
    const { id, data } = props ?? {};

    return atualizarCategorias(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarCategoriasMutationResult = NonNullable<
  Awaited<ReturnType<typeof atualizarCategorias>>
>;
export type AtualizarCategoriasMutationBody = AtualizacaoCategoriaDto;
export type AtualizarCategoriasMutationError = unknown;
export type AtualizarCategoriasMutationVariables = { id: string; data: AtualizacaoCategoriaDto };

export const useAtualizarCategorias = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarCategorias>>,
      TError,
      AtualizarCategoriasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarCategorias>>,
  TError,
  AtualizarCategoriasMutationVariables,
  TContext
> => {
  return useMutation(getAtualizarCategoriasMutationOptions(options), queryClient);
};
export const getExcluirCategoriasUrl = (id: string, params?: ExcluirCategoriasParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/categorias/${id}?${stringifiedParams}`
    : `/v1/categorias/${id}`;
};

export const excluirCategorias = async (
  id: string,
  params?: ExcluirCategoriasParams,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  return requisicao<void>(getExcluirCategoriasUrl(id, params), {
    ...options,
    method: 'DELETE',
  });
};

export const getExcluirCategoriasMutationKey = () => ['excluirCategorias'] as const;

export const getExcluirCategoriasMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof excluirCategorias>>,
    TError,
    ExcluirCategoriasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof excluirCategorias>>,
  TError,
  ExcluirCategoriasMutationVariables,
  TContext
> => {
  const mutationKey = getExcluirCategoriasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof excluirCategorias>>,
    ExcluirCategoriasMutationVariables
  > = (props) => {
    const { id, params } = props ?? {};

    return excluirCategorias(id, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExcluirCategoriasMutationResult = NonNullable<
  Awaited<ReturnType<typeof excluirCategorias>>
>;

export type ExcluirCategoriasMutationError = unknown;
export type ExcluirCategoriasMutationVariables = { id: string; params?: ExcluirCategoriasParams };

export const useExcluirCategorias = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof excluirCategorias>>,
      TError,
      ExcluirCategoriasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof excluirCategorias>>,
  TError,
  ExcluirCategoriasMutationVariables,
  TContext
> => {
  return useMutation(getExcluirCategoriasMutationOptions(options), queryClient);
};
