/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AtualizacaoMetaDto,
  DetalheMetaDto,
  ListaMetasDto,
  MetaDto,
  NovaMetaDto,
  NovoAporteDto,
  RespostaAporteDto,
} from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListarMetasUrl = () => {
  return `/v1/metas`;
};

export const listarMetas = async (
  options?: Parameters<typeof requisicao>[1],
): Promise<ListaMetasDto> => {
  return requisicao<ListaMetasDto>(getListarMetasUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getListarMetasQueryKey = () => {
  return [`/v1/metas`] as const;
};

export const getListarMetasQueryOptions = <
  TData = Awaited<ReturnType<typeof listarMetas>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarMetas>>, TError, TData>>;
  request?: SecondParameter<typeof requisicao>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListarMetasQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listarMetas>>> = ({ signal }) =>
    listarMetas({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listarMetas>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListarMetasQueryResult = NonNullable<Awaited<ReturnType<typeof listarMetas>>>;
export type ListarMetasQueryError = unknown;

export function useListarMetas<TData = Awaited<ReturnType<typeof listarMetas>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarMetas>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarMetas>>,
          TError,
          Awaited<ReturnType<typeof listarMetas>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarMetas<TData = Awaited<ReturnType<typeof listarMetas>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarMetas>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarMetas>>,
          TError,
          Awaited<ReturnType<typeof listarMetas>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarMetas<TData = Awaited<ReturnType<typeof listarMetas>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarMetas>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListarMetas<TData = Awaited<ReturnType<typeof listarMetas>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarMetas>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListarMetasQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getCriarMetasUrl = () => {
  return `/v1/metas`;
};

export const criarMetas = async (
  novaMetaDto: NovaMetaDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<MetaDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<MetaDto>(getCriarMetasUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(novaMetaDto),
  });
};

export const getCriarMetasMutationKey = () => ['criarMetas'] as const;

export const getCriarMetasMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarMetas>>,
    TError,
    CriarMetasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarMetas>>,
  TError,
  CriarMetasMutationVariables,
  TContext
> => {
  const mutationKey = getCriarMetasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarMetas>>,
    CriarMetasMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return criarMetas(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarMetasMutationResult = NonNullable<Awaited<ReturnType<typeof criarMetas>>>;
export type CriarMetasMutationBody = NovaMetaDto;
export type CriarMetasMutationError = unknown;
export type CriarMetasMutationVariables = { data: NovaMetaDto };

export const useCriarMetas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarMetas>>,
      TError,
      CriarMetasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarMetas>>,
  TError,
  CriarMetasMutationVariables,
  TContext
> => {
  return useMutation(getCriarMetasMutationOptions(options), queryClient);
};
export const getBuscarMetasUrl = (id: string) => {
  return `/v1/metas/${id}`;
};

export const buscarMetas = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<DetalheMetaDto> => {
  return requisicao<DetalheMetaDto>(getBuscarMetasUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getBuscarMetasQueryKey = (id: string) => {
  return [`/v1/metas/${id}`] as const;
};

export const getBuscarMetasQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarMetas>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarMetas>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBuscarMetasQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof buscarMetas>>> = ({ signal }) =>
    buscarMetas(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof buscarMetas>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type BuscarMetasQueryResult = NonNullable<Awaited<ReturnType<typeof buscarMetas>>>;
export type BuscarMetasQueryError = unknown;

export function useBuscarMetas<TData = Awaited<ReturnType<typeof buscarMetas>>, TError = unknown>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarMetas>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarMetas>>,
          TError,
          Awaited<ReturnType<typeof buscarMetas>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarMetas<TData = Awaited<ReturnType<typeof buscarMetas>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarMetas>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarMetas>>,
          TError,
          Awaited<ReturnType<typeof buscarMetas>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarMetas<TData = Awaited<ReturnType<typeof buscarMetas>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarMetas>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBuscarMetas<TData = Awaited<ReturnType<typeof buscarMetas>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarMetas>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBuscarMetasQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getAtualizarMetasUrl = (id: string) => {
  return `/v1/metas/${id}`;
};

export const atualizarMetas = async (
  id: string,
  atualizacaoMetaDto: AtualizacaoMetaDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<MetaDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<MetaDto>(getAtualizarMetasUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizacaoMetaDto),
  });
};

export const getAtualizarMetasMutationKey = () => ['atualizarMetas'] as const;

export const getAtualizarMetasMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarMetas>>,
    TError,
    AtualizarMetasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarMetas>>,
  TError,
  AtualizarMetasMutationVariables,
  TContext
> => {
  const mutationKey = getAtualizarMetasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarMetas>>,
    AtualizarMetasMutationVariables
  > = (props) => {
    const { id, data } = props ?? {};

    return atualizarMetas(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarMetasMutationResult = NonNullable<Awaited<ReturnType<typeof atualizarMetas>>>;
export type AtualizarMetasMutationBody = AtualizacaoMetaDto;
export type AtualizarMetasMutationError = unknown;
export type AtualizarMetasMutationVariables = { id: string; data: AtualizacaoMetaDto };

export const useAtualizarMetas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarMetas>>,
      TError,
      AtualizarMetasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarMetas>>,
  TError,
  AtualizarMetasMutationVariables,
  TContext
> => {
  return useMutation(getAtualizarMetasMutationOptions(options), queryClient);
};
export const getExcluirMetasUrl = (id: string) => {
  return `/v1/metas/${id}`;
};

export const excluirMetas = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  return requisicao<void>(getExcluirMetasUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getExcluirMetasMutationKey = () => ['excluirMetas'] as const;

export const getExcluirMetasMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof excluirMetas>>,
    TError,
    ExcluirMetasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof excluirMetas>>,
  TError,
  ExcluirMetasMutationVariables,
  TContext
> => {
  const mutationKey = getExcluirMetasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof excluirMetas>>,
    ExcluirMetasMutationVariables
  > = (props) => {
    const { id } = props ?? {};

    return excluirMetas(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExcluirMetasMutationResult = NonNullable<Awaited<ReturnType<typeof excluirMetas>>>;

export type ExcluirMetasMutationError = unknown;
export type ExcluirMetasMutationVariables = { id: string };

export const useExcluirMetas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof excluirMetas>>,
      TError,
      ExcluirMetasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof excluirMetas>>,
  TError,
  ExcluirMetasMutationVariables,
  TContext
> => {
  return useMutation(getExcluirMetasMutationOptions(options), queryClient);
};
export const getAportarMetasUrl = (id: string) => {
  return `/v1/metas/${id}/aportes`;
};

export const aportarMetas = async (
  id: string,
  novoAporteDto: NovoAporteDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<RespostaAporteDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<RespostaAporteDto>(getAportarMetasUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(novoAporteDto),
  });
};

export const getAportarMetasMutationKey = () => ['aportarMetas'] as const;

export const getAportarMetasMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof aportarMetas>>,
    TError,
    AportarMetasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof aportarMetas>>,
  TError,
  AportarMetasMutationVariables,
  TContext
> => {
  const mutationKey = getAportarMetasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof aportarMetas>>,
    AportarMetasMutationVariables
  > = (props) => {
    const { id, data } = props ?? {};

    return aportarMetas(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AportarMetasMutationResult = NonNullable<Awaited<ReturnType<typeof aportarMetas>>>;
export type AportarMetasMutationBody = NovoAporteDto;
export type AportarMetasMutationError = unknown;
export type AportarMetasMutationVariables = { id: string; data: NovoAporteDto };

export const useAportarMetas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof aportarMetas>>,
      TError,
      AportarMetasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof aportarMetas>>,
  TError,
  AportarMetasMutationVariables,
  TContext
> => {
  return useMutation(getAportarMetasMutationOptions(options), queryClient);
};
export const getExcluirAporteMetasUrl = (id: string, aporteId: string) => {
  return `/v1/metas/${id}/aportes/${aporteId}`;
};

export const excluirAporteMetas = async (
  id: string,
  aporteId: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<MetaDto> => {
  return requisicao<MetaDto>(getExcluirAporteMetasUrl(id, aporteId), {
    ...options,
    method: 'DELETE',
  });
};

export const getExcluirAporteMetasMutationKey = () => ['excluirAporteMetas'] as const;

export const getExcluirAporteMetasMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof excluirAporteMetas>>,
    TError,
    ExcluirAporteMetasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof excluirAporteMetas>>,
  TError,
  ExcluirAporteMetasMutationVariables,
  TContext
> => {
  const mutationKey = getExcluirAporteMetasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof excluirAporteMetas>>,
    ExcluirAporteMetasMutationVariables
  > = (props) => {
    const { id, aporteId } = props ?? {};

    return excluirAporteMetas(id, aporteId, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExcluirAporteMetasMutationResult = NonNullable<
  Awaited<ReturnType<typeof excluirAporteMetas>>
>;

export type ExcluirAporteMetasMutationError = unknown;
export type ExcluirAporteMetasMutationVariables = { id: string; aporteId: string };

export const useExcluirAporteMetas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof excluirAporteMetas>>,
      TError,
      ExcluirAporteMetasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof excluirAporteMetas>>,
  TError,
  ExcluirAporteMetasMutationVariables,
  TContext
> => {
  return useMutation(getExcluirAporteMetasMutationOptions(options), queryClient);
};
