/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { ConfigAppDto } from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getObterConfigAppUrl = () => {
  return `/v1/config-app`;
};

export const obterConfigApp = async (
  options?: Parameters<typeof requisicao>[1],
): Promise<ConfigAppDto> => {
  return requisicao<ConfigAppDto>(getObterConfigAppUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getObterConfigAppQueryKey = () => {
  return [`/v1/config-app`] as const;
};

export const getObterConfigAppQueryOptions = <
  TData = Awaited<ReturnType<typeof obterConfigApp>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof obterConfigApp>>, TError, TData>>;
  request?: SecondParameter<typeof requisicao>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getObterConfigAppQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof obterConfigApp>>> = ({ signal }) =>
    obterConfigApp({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof obterConfigApp>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ObterConfigAppQueryResult = NonNullable<Awaited<ReturnType<typeof obterConfigApp>>>;
export type ObterConfigAppQueryError = unknown;

export function useObterConfigApp<
  TData = Awaited<ReturnType<typeof obterConfigApp>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof obterConfigApp>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obterConfigApp>>,
          TError,
          Awaited<ReturnType<typeof obterConfigApp>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useObterConfigApp<
  TData = Awaited<ReturnType<typeof obterConfigApp>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof obterConfigApp>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obterConfigApp>>,
          TError,
          Awaited<ReturnType<typeof obterConfigApp>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useObterConfigApp<
  TData = Awaited<ReturnType<typeof obterConfigApp>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof obterConfigApp>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useObterConfigApp<
  TData = Awaited<ReturnType<typeof obterConfigApp>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof obterConfigApp>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getObterConfigAppQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
