/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AtualizacaoCartaoDto,
  CartaoDto,
  DetalheFaturaDto,
  ListaCartoesDto,
  ListaFaturasDto,
  NovoCartaoDto,
  PagamentoFaturaDto,
  RespostaPagamentoFaturaDto,
} from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListarCartoesUrl = () => {
  return `/v1/cartoes`;
};

export const listarCartoes = async (
  options?: Parameters<typeof requisicao>[1],
): Promise<ListaCartoesDto> => {
  return requisicao<ListaCartoesDto>(getListarCartoesUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getListarCartoesQueryKey = () => {
  return [`/v1/cartoes`] as const;
};

export const getListarCartoesQueryOptions = <
  TData = Awaited<ReturnType<typeof listarCartoes>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCartoes>>, TError, TData>>;
  request?: SecondParameter<typeof requisicao>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListarCartoesQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listarCartoes>>> = ({ signal }) =>
    listarCartoes({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listarCartoes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListarCartoesQueryResult = NonNullable<Awaited<ReturnType<typeof listarCartoes>>>;
export type ListarCartoesQueryError = unknown;

export function useListarCartoes<
  TData = Awaited<ReturnType<typeof listarCartoes>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCartoes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarCartoes>>,
          TError,
          Awaited<ReturnType<typeof listarCartoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarCartoes<
  TData = Awaited<ReturnType<typeof listarCartoes>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCartoes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarCartoes>>,
          TError,
          Awaited<ReturnType<typeof listarCartoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarCartoes<
  TData = Awaited<ReturnType<typeof listarCartoes>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCartoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListarCartoes<
  TData = Awaited<ReturnType<typeof listarCartoes>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarCartoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListarCartoesQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getCriarCartoesUrl = () => {
  return `/v1/cartoes`;
};

export const criarCartoes = async (
  novoCartaoDto: NovoCartaoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<CartaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<CartaoDto>(getCriarCartoesUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(novoCartaoDto),
  });
};

export const getCriarCartoesMutationKey = () => ['criarCartoes'] as const;

export const getCriarCartoesMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarCartoes>>,
    TError,
    CriarCartoesMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarCartoes>>,
  TError,
  CriarCartoesMutationVariables,
  TContext
> => {
  const mutationKey = getCriarCartoesMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarCartoes>>,
    CriarCartoesMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return criarCartoes(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarCartoesMutationResult = NonNullable<Awaited<ReturnType<typeof criarCartoes>>>;
export type CriarCartoesMutationBody = NovoCartaoDto;
export type CriarCartoesMutationError = unknown;
export type CriarCartoesMutationVariables = { data: NovoCartaoDto };

export const useCriarCartoes = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarCartoes>>,
      TError,
      CriarCartoesMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarCartoes>>,
  TError,
  CriarCartoesMutationVariables,
  TContext
> => {
  return useMutation(getCriarCartoesMutationOptions(options), queryClient);
};
export const getBuscarCartoesUrl = (id: string) => {
  return `/v1/cartoes/${id}`;
};

export const buscarCartoes = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<CartaoDto> => {
  return requisicao<CartaoDto>(getBuscarCartoesUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getBuscarCartoesQueryKey = (id: string) => {
  return [`/v1/cartoes/${id}`] as const;
};

export const getBuscarCartoesQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarCartoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarCartoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBuscarCartoesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof buscarCartoes>>> = ({ signal }) =>
    buscarCartoes(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof buscarCartoes>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type BuscarCartoesQueryResult = NonNullable<Awaited<ReturnType<typeof buscarCartoes>>>;
export type BuscarCartoesQueryError = unknown;

export function useBuscarCartoes<
  TData = Awaited<ReturnType<typeof buscarCartoes>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarCartoes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarCartoes>>,
          TError,
          Awaited<ReturnType<typeof buscarCartoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarCartoes<
  TData = Awaited<ReturnType<typeof buscarCartoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarCartoes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarCartoes>>,
          TError,
          Awaited<ReturnType<typeof buscarCartoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarCartoes<
  TData = Awaited<ReturnType<typeof buscarCartoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarCartoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBuscarCartoes<
  TData = Awaited<ReturnType<typeof buscarCartoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarCartoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBuscarCartoesQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getAtualizarCartoesUrl = (id: string) => {
  return `/v1/cartoes/${id}`;
};

export const atualizarCartoes = async (
  id: string,
  atualizacaoCartaoDto: AtualizacaoCartaoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<CartaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<CartaoDto>(getAtualizarCartoesUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizacaoCartaoDto),
  });
};

export const getAtualizarCartoesMutationKey = () => ['atualizarCartoes'] as const;

export const getAtualizarCartoesMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarCartoes>>,
    TError,
    AtualizarCartoesMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarCartoes>>,
  TError,
  AtualizarCartoesMutationVariables,
  TContext
> => {
  const mutationKey = getAtualizarCartoesMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarCartoes>>,
    AtualizarCartoesMutationVariables
  > = (props) => {
    const { id, data } = props ?? {};

    return atualizarCartoes(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarCartoesMutationResult = NonNullable<
  Awaited<ReturnType<typeof atualizarCartoes>>
>;
export type AtualizarCartoesMutationBody = AtualizacaoCartaoDto;
export type AtualizarCartoesMutationError = unknown;
export type AtualizarCartoesMutationVariables = { id: string; data: AtualizacaoCartaoDto };

export const useAtualizarCartoes = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarCartoes>>,
      TError,
      AtualizarCartoesMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarCartoes>>,
  TError,
  AtualizarCartoesMutationVariables,
  TContext
> => {
  return useMutation(getAtualizarCartoesMutationOptions(options), queryClient);
};
export const getExcluirCartoesUrl = (id: string) => {
  return `/v1/cartoes/${id}`;
};

export const excluirCartoes = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  return requisicao<void>(getExcluirCartoesUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getExcluirCartoesMutationKey = () => ['excluirCartoes'] as const;

export const getExcluirCartoesMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof excluirCartoes>>,
    TError,
    ExcluirCartoesMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof excluirCartoes>>,
  TError,
  ExcluirCartoesMutationVariables,
  TContext
> => {
  const mutationKey = getExcluirCartoesMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof excluirCartoes>>,
    ExcluirCartoesMutationVariables
  > = (props) => {
    const { id } = props ?? {};

    return excluirCartoes(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExcluirCartoesMutationResult = NonNullable<Awaited<ReturnType<typeof excluirCartoes>>>;

export type ExcluirCartoesMutationError = unknown;
export type ExcluirCartoesMutationVariables = { id: string };

export const useExcluirCartoes = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof excluirCartoes>>,
      TError,
      ExcluirCartoesMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof excluirCartoes>>,
  TError,
  ExcluirCartoesMutationVariables,
  TContext
> => {
  return useMutation(getExcluirCartoesMutationOptions(options), queryClient);
};
export const getFaturasCartoesUrl = (id: string) => {
  return `/v1/cartoes/${id}/faturas`;
};

export const faturasCartoes = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<ListaFaturasDto> => {
  return requisicao<ListaFaturasDto>(getFaturasCartoesUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getFaturasCartoesQueryKey = (id: string) => {
  return [`/v1/cartoes/${id}/faturas`] as const;
};

export const getFaturasCartoesQueryOptions = <
  TData = Awaited<ReturnType<typeof faturasCartoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof faturasCartoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getFaturasCartoesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof faturasCartoes>>> = ({ signal }) =>
    faturasCartoes(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof faturasCartoes>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type FaturasCartoesQueryResult = NonNullable<Awaited<ReturnType<typeof faturasCartoes>>>;
export type FaturasCartoesQueryError = unknown;

export function useFaturasCartoes<
  TData = Awaited<ReturnType<typeof faturasCartoes>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof faturasCartoes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof faturasCartoes>>,
          TError,
          Awaited<ReturnType<typeof faturasCartoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFaturasCartoes<
  TData = Awaited<ReturnType<typeof faturasCartoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof faturasCartoes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof faturasCartoes>>,
          TError,
          Awaited<ReturnType<typeof faturasCartoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useFaturasCartoes<
  TData = Awaited<ReturnType<typeof faturasCartoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof faturasCartoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useFaturasCartoes<
  TData = Awaited<ReturnType<typeof faturasCartoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof faturasCartoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getFaturasCartoesQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getBuscarFaturasUrl = (id: string) => {
  return `/v1/faturas/${id}`;
};

export const buscarFaturas = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<DetalheFaturaDto> => {
  return requisicao<DetalheFaturaDto>(getBuscarFaturasUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getBuscarFaturasQueryKey = (id: string) => {
  return [`/v1/faturas/${id}`] as const;
};

export const getBuscarFaturasQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarFaturas>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarFaturas>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBuscarFaturasQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof buscarFaturas>>> = ({ signal }) =>
    buscarFaturas(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof buscarFaturas>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type BuscarFaturasQueryResult = NonNullable<Awaited<ReturnType<typeof buscarFaturas>>>;
export type BuscarFaturasQueryError = unknown;

export function useBuscarFaturas<
  TData = Awaited<ReturnType<typeof buscarFaturas>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarFaturas>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarFaturas>>,
          TError,
          Awaited<ReturnType<typeof buscarFaturas>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarFaturas<
  TData = Awaited<ReturnType<typeof buscarFaturas>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarFaturas>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarFaturas>>,
          TError,
          Awaited<ReturnType<typeof buscarFaturas>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarFaturas<
  TData = Awaited<ReturnType<typeof buscarFaturas>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarFaturas>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBuscarFaturas<
  TData = Awaited<ReturnType<typeof buscarFaturas>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarFaturas>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBuscarFaturasQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getPagarFaturasUrl = (id: string) => {
  return `/v1/faturas/${id}/pagar`;
};

export const pagarFaturas = async (
  id: string,
  pagamentoFaturaDto: PagamentoFaturaDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<RespostaPagamentoFaturaDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<RespostaPagamentoFaturaDto>(getPagarFaturasUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pagamentoFaturaDto),
  });
};

export const getPagarFaturasMutationKey = () => ['pagarFaturas'] as const;

export const getPagarFaturasMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pagarFaturas>>,
    TError,
    PagarFaturasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pagarFaturas>>,
  TError,
  PagarFaturasMutationVariables,
  TContext
> => {
  const mutationKey = getPagarFaturasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pagarFaturas>>,
    PagarFaturasMutationVariables
  > = (props) => {
    const { id, data } = props ?? {};

    return pagarFaturas(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PagarFaturasMutationResult = NonNullable<Awaited<ReturnType<typeof pagarFaturas>>>;
export type PagarFaturasMutationBody = PagamentoFaturaDto;
export type PagarFaturasMutationError = unknown;
export type PagarFaturasMutationVariables = { id: string; data: PagamentoFaturaDto };

export const usePagarFaturas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pagarFaturas>>,
      TError,
      PagarFaturasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pagarFaturas>>,
  TError,
  PagarFaturasMutationVariables,
  TContext
> => {
  return useMutation(getPagarFaturasMutationOptions(options), queryClient);
};
