/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { DashboardDto, ObterDashboardParams } from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getObterDashboardUrl = (params?: ObterDashboardParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/dashboard?${stringifiedParams}` : `/v1/dashboard`;
};

export const obterDashboard = async (
  params?: ObterDashboardParams,
  options?: Parameters<typeof requisicao>[1],
): Promise<DashboardDto> => {
  return requisicao<DashboardDto>(getObterDashboardUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getObterDashboardQueryKey = (params?: ObterDashboardParams) => {
  return [`/v1/dashboard`, ...(params ? [params] : [])] as const;
};

export const getObterDashboardQueryOptions = <
  TData = Awaited<ReturnType<typeof obterDashboard>>,
  TError = unknown,
>(
  params?: ObterDashboardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof obterDashboard>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getObterDashboardQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof obterDashboard>>> = ({ signal }) =>
    obterDashboard(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof obterDashboard>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ObterDashboardQueryResult = NonNullable<Awaited<ReturnType<typeof obterDashboard>>>;
export type ObterDashboardQueryError = unknown;

export function useObterDashboard<
  TData = Awaited<ReturnType<typeof obterDashboard>>,
  TError = unknown,
>(
  params: undefined | ObterDashboardParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof obterDashboard>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof obterDashboard>>,
          TError,
          Awaited<ReturnType<typeof obterDashboard>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useObterDashboard<
  TData = Awaited<ReturnType<typeof obterDashboard>>,
  TError = unknown,
>(
  params?: ObterDashboardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof obterDashboard>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof obterDashboard>>,
          TError,
          Awaited<ReturnType<typeof obterDashboard>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useObterDashboard<
  TData = Awaited<ReturnType<typeof obterDashboard>>,
  TError = unknown,
>(
  params?: ObterDashboardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof obterDashboard>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useObterDashboard<
  TData = Awaited<ReturnType<typeof obterDashboard>>,
  TError = unknown,
>(
  params?: ObterDashboardParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof obterDashboard>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getObterDashboardQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
