/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type { CadastroDto, LoginDto, RenovacaoDto, SessaoDto } from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getCadastrarAutenticacaoUrl = () => {
  return `/v1/auth/cadastro`;
};

export const cadastrarAutenticacao = async (
  cadastroDto: CadastroDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<SessaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<SessaoDto>(getCadastrarAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(cadastroDto),
  });
};

export const getCadastrarAutenticacaoMutationKey = () => ['cadastrarAutenticacao'] as const;

export const getCadastrarAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cadastrarAutenticacao>>,
    TError,
    CadastrarAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cadastrarAutenticacao>>,
  TError,
  CadastrarAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getCadastrarAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cadastrarAutenticacao>>,
    CadastrarAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return cadastrarAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CadastrarAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof cadastrarAutenticacao>>
>;
export type CadastrarAutenticacaoMutationBody = CadastroDto;
export type CadastrarAutenticacaoMutationError = unknown;
export type CadastrarAutenticacaoMutationVariables = { data: CadastroDto };

export const useCadastrarAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cadastrarAutenticacao>>,
      TError,
      CadastrarAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cadastrarAutenticacao>>,
  TError,
  CadastrarAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getCadastrarAutenticacaoMutationOptions(options), queryClient);
};
export const getEntrarAutenticacaoUrl = () => {
  return `/v1/auth/login`;
};

export const entrarAutenticacao = async (
  loginDto: LoginDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<SessaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<SessaoDto>(getEntrarAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginDto),
  });
};

export const getEntrarAutenticacaoMutationKey = () => ['entrarAutenticacao'] as const;

export const getEntrarAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof entrarAutenticacao>>,
    TError,
    EntrarAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof entrarAutenticacao>>,
  TError,
  EntrarAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getEntrarAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof entrarAutenticacao>>,
    EntrarAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return entrarAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EntrarAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof entrarAutenticacao>>
>;
export type EntrarAutenticacaoMutationBody = LoginDto;
export type EntrarAutenticacaoMutationError = unknown;
export type EntrarAutenticacaoMutationVariables = { data: LoginDto };

export const useEntrarAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof entrarAutenticacao>>,
      TError,
      EntrarAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof entrarAutenticacao>>,
  TError,
  EntrarAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getEntrarAutenticacaoMutationOptions(options), queryClient);
};
export const getRenovarAutenticacaoUrl = () => {
  return `/v1/auth/renovar`;
};

export const renovarAutenticacao = async (
  renovacaoDto: RenovacaoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<SessaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<SessaoDto>(getRenovarAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(renovacaoDto),
  });
};

export const getRenovarAutenticacaoMutationKey = () => ['renovarAutenticacao'] as const;

export const getRenovarAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof renovarAutenticacao>>,
    TError,
    RenovarAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof renovarAutenticacao>>,
  TError,
  RenovarAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getRenovarAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof renovarAutenticacao>>,
    RenovarAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return renovarAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RenovarAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof renovarAutenticacao>>
>;
export type RenovarAutenticacaoMutationBody = RenovacaoDto;
export type RenovarAutenticacaoMutationError = unknown;
export type RenovarAutenticacaoMutationVariables = { data: RenovacaoDto };

export const useRenovarAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof renovarAutenticacao>>,
      TError,
      RenovarAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof renovarAutenticacao>>,
  TError,
  RenovarAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getRenovarAutenticacaoMutationOptions(options), queryClient);
};
export const getSairAutenticacaoUrl = () => {
  return `/v1/auth/sair`;
};

export const sairAutenticacao = async (
  renovacaoDto: RenovacaoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<void>(getSairAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(renovacaoDto),
  });
};

export const getSairAutenticacaoMutationKey = () => ['sairAutenticacao'] as const;

export const getSairAutenticacaoMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sairAutenticacao>>,
    TError,
    SairAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sairAutenticacao>>,
  TError,
  SairAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getSairAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sairAutenticacao>>,
    SairAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return sairAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SairAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof sairAutenticacao>>
>;
export type SairAutenticacaoMutationBody = RenovacaoDto;
export type SairAutenticacaoMutationError = unknown;
export type SairAutenticacaoMutationVariables = { data: RenovacaoDto };

export const useSairAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sairAutenticacao>>,
      TError,
      SairAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sairAutenticacao>>,
  TError,
  SairAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getSairAutenticacaoMutationOptions(options), queryClient);
};
export const getSairDeTodosAutenticacaoUrl = () => {
  return `/v1/auth/sair-todos`;
};

export const sairDeTodosAutenticacao = async (
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  return requisicao<void>(getSairDeTodosAutenticacaoUrl(), {
    ...options,
    method: 'POST',
  });
};

export const getSairDeTodosAutenticacaoMutationKey = () => ['sairDeTodosAutenticacao'] as const;

export const getSairDeTodosAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sairDeTodosAutenticacao>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sairDeTodosAutenticacao>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getSairDeTodosAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sairDeTodosAutenticacao>>,
    void
  > = () => {
    return sairDeTodosAutenticacao(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SairDeTodosAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof sairDeTodosAutenticacao>>
>;

export type SairDeTodosAutenticacaoMutationError = unknown;

export const useSairDeTodosAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sairDeTodosAutenticacao>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sairDeTodosAutenticacao>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getSairDeTodosAutenticacaoMutationOptions(options), queryClient);
};
