/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation } from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryClient,
  UseMutationOptions,
  UseMutationResult,
} from '@tanstack/react-query';

import type {
  CadastroDto,
  ConferenciaCodigoDto,
  LoginDto,
  LoginSocialDto,
  PedidoCodigoDto,
  RedefinicaoSenhaDto,
  RenovacaoDto,
  SessaoDto,
  VinculoSocialDto,
} from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const getCadastrarAutenticacaoUrl = () => {
  return `/v1/auth/cadastro`;
};

export const cadastrarAutenticacao = async (
  cadastroDto: CadastroDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<SessaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<SessaoDto>(getCadastrarAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(cadastroDto),
  });
};

export const getCadastrarAutenticacaoMutationKey = () => ['cadastrarAutenticacao'] as const;

export const getCadastrarAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cadastrarAutenticacao>>,
    TError,
    CadastrarAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cadastrarAutenticacao>>,
  TError,
  CadastrarAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getCadastrarAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cadastrarAutenticacao>>,
    CadastrarAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return cadastrarAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CadastrarAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof cadastrarAutenticacao>>
>;
export type CadastrarAutenticacaoMutationBody = CadastroDto;
export type CadastrarAutenticacaoMutationError = unknown;
export type CadastrarAutenticacaoMutationVariables = { data: CadastroDto };

export const useCadastrarAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cadastrarAutenticacao>>,
      TError,
      CadastrarAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cadastrarAutenticacao>>,
  TError,
  CadastrarAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getCadastrarAutenticacaoMutationOptions(options), queryClient);
};
export const getEntrarAutenticacaoUrl = () => {
  return `/v1/auth/login`;
};

export const entrarAutenticacao = async (
  loginDto: LoginDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<SessaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<SessaoDto>(getEntrarAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginDto),
  });
};

export const getEntrarAutenticacaoMutationKey = () => ['entrarAutenticacao'] as const;

export const getEntrarAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof entrarAutenticacao>>,
    TError,
    EntrarAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof entrarAutenticacao>>,
  TError,
  EntrarAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getEntrarAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof entrarAutenticacao>>,
    EntrarAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return entrarAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EntrarAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof entrarAutenticacao>>
>;
export type EntrarAutenticacaoMutationBody = LoginDto;
export type EntrarAutenticacaoMutationError = unknown;
export type EntrarAutenticacaoMutationVariables = { data: LoginDto };

export const useEntrarAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof entrarAutenticacao>>,
      TError,
      EntrarAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof entrarAutenticacao>>,
  TError,
  EntrarAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getEntrarAutenticacaoMutationOptions(options), queryClient);
};
export const getEntrarComLoginSocialAutenticacaoUrl = () => {
  return `/v1/auth/social`;
};

export const entrarComLoginSocialAutenticacao = async (
  loginSocialDto: LoginSocialDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<SessaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<SessaoDto>(getEntrarComLoginSocialAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loginSocialDto),
  });
};

export const getEntrarComLoginSocialAutenticacaoMutationKey = () =>
  ['entrarComLoginSocialAutenticacao'] as const;

export const getEntrarComLoginSocialAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof entrarComLoginSocialAutenticacao>>,
    TError,
    EntrarComLoginSocialAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof entrarComLoginSocialAutenticacao>>,
  TError,
  EntrarComLoginSocialAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getEntrarComLoginSocialAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof entrarComLoginSocialAutenticacao>>,
    EntrarComLoginSocialAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return entrarComLoginSocialAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type EntrarComLoginSocialAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof entrarComLoginSocialAutenticacao>>
>;
export type EntrarComLoginSocialAutenticacaoMutationBody = LoginSocialDto;
export type EntrarComLoginSocialAutenticacaoMutationError = unknown;
export type EntrarComLoginSocialAutenticacaoMutationVariables = { data: LoginSocialDto };

export const useEntrarComLoginSocialAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof entrarComLoginSocialAutenticacao>>,
      TError,
      EntrarComLoginSocialAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof entrarComLoginSocialAutenticacao>>,
  TError,
  EntrarComLoginSocialAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getEntrarComLoginSocialAutenticacaoMutationOptions(options), queryClient);
};
export const getVincularLoginSocialAutenticacaoUrl = () => {
  return `/v1/auth/social/vincular`;
};

export const vincularLoginSocialAutenticacao = async (
  vinculoSocialDto: VinculoSocialDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<void>(getVincularLoginSocialAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(vinculoSocialDto),
  });
};

export const getVincularLoginSocialAutenticacaoMutationKey = () =>
  ['vincularLoginSocialAutenticacao'] as const;

export const getVincularLoginSocialAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof vincularLoginSocialAutenticacao>>,
    TError,
    VincularLoginSocialAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof vincularLoginSocialAutenticacao>>,
  TError,
  VincularLoginSocialAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getVincularLoginSocialAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof vincularLoginSocialAutenticacao>>,
    VincularLoginSocialAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return vincularLoginSocialAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type VincularLoginSocialAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof vincularLoginSocialAutenticacao>>
>;
export type VincularLoginSocialAutenticacaoMutationBody = VinculoSocialDto;
export type VincularLoginSocialAutenticacaoMutationError = unknown;
export type VincularLoginSocialAutenticacaoMutationVariables = { data: VinculoSocialDto };

export const useVincularLoginSocialAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof vincularLoginSocialAutenticacao>>,
      TError,
      VincularLoginSocialAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof vincularLoginSocialAutenticacao>>,
  TError,
  VincularLoginSocialAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getVincularLoginSocialAutenticacaoMutationOptions(options), queryClient);
};
export const getRenovarAutenticacaoUrl = () => {
  return `/v1/auth/renovar`;
};

export const renovarAutenticacao = async (
  renovacaoDto: RenovacaoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<SessaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<SessaoDto>(getRenovarAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(renovacaoDto),
  });
};

export const getRenovarAutenticacaoMutationKey = () => ['renovarAutenticacao'] as const;

export const getRenovarAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof renovarAutenticacao>>,
    TError,
    RenovarAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof renovarAutenticacao>>,
  TError,
  RenovarAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getRenovarAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof renovarAutenticacao>>,
    RenovarAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return renovarAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RenovarAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof renovarAutenticacao>>
>;
export type RenovarAutenticacaoMutationBody = RenovacaoDto;
export type RenovarAutenticacaoMutationError = unknown;
export type RenovarAutenticacaoMutationVariables = { data: RenovacaoDto };

export const useRenovarAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof renovarAutenticacao>>,
      TError,
      RenovarAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof renovarAutenticacao>>,
  TError,
  RenovarAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getRenovarAutenticacaoMutationOptions(options), queryClient);
};
export const getSairAutenticacaoUrl = () => {
  return `/v1/auth/sair`;
};

export const sairAutenticacao = async (
  renovacaoDto: RenovacaoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<void>(getSairAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(renovacaoDto),
  });
};

export const getSairAutenticacaoMutationKey = () => ['sairAutenticacao'] as const;

export const getSairAutenticacaoMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sairAutenticacao>>,
    TError,
    SairAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sairAutenticacao>>,
  TError,
  SairAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getSairAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sairAutenticacao>>,
    SairAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return sairAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SairAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof sairAutenticacao>>
>;
export type SairAutenticacaoMutationBody = RenovacaoDto;
export type SairAutenticacaoMutationError = unknown;
export type SairAutenticacaoMutationVariables = { data: RenovacaoDto };

export const useSairAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sairAutenticacao>>,
      TError,
      SairAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sairAutenticacao>>,
  TError,
  SairAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getSairAutenticacaoMutationOptions(options), queryClient);
};
export const getPedirCodigoSenhaAutenticacaoUrl = () => {
  return `/v1/auth/senha/codigo`;
};

export const pedirCodigoSenhaAutenticacao = async (
  pedidoCodigoDto: PedidoCodigoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<void>(getPedirCodigoSenhaAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pedidoCodigoDto),
  });
};

export const getPedirCodigoSenhaAutenticacaoMutationKey = () =>
  ['pedirCodigoSenhaAutenticacao'] as const;

export const getPedirCodigoSenhaAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pedirCodigoSenhaAutenticacao>>,
    TError,
    PedirCodigoSenhaAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pedirCodigoSenhaAutenticacao>>,
  TError,
  PedirCodigoSenhaAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getPedirCodigoSenhaAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pedirCodigoSenhaAutenticacao>>,
    PedirCodigoSenhaAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return pedirCodigoSenhaAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PedirCodigoSenhaAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof pedirCodigoSenhaAutenticacao>>
>;
export type PedirCodigoSenhaAutenticacaoMutationBody = PedidoCodigoDto;
export type PedirCodigoSenhaAutenticacaoMutationError = unknown;
export type PedirCodigoSenhaAutenticacaoMutationVariables = { data: PedidoCodigoDto };

export const usePedirCodigoSenhaAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pedirCodigoSenhaAutenticacao>>,
      TError,
      PedirCodigoSenhaAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pedirCodigoSenhaAutenticacao>>,
  TError,
  PedirCodigoSenhaAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getPedirCodigoSenhaAutenticacaoMutationOptions(options), queryClient);
};
export const getConferirCodigoSenhaAutenticacaoUrl = () => {
  return `/v1/auth/senha/conferir`;
};

export const conferirCodigoSenhaAutenticacao = async (
  conferenciaCodigoDto: ConferenciaCodigoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<void>(getConferirCodigoSenhaAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(conferenciaCodigoDto),
  });
};

export const getConferirCodigoSenhaAutenticacaoMutationKey = () =>
  ['conferirCodigoSenhaAutenticacao'] as const;

export const getConferirCodigoSenhaAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof conferirCodigoSenhaAutenticacao>>,
    TError,
    ConferirCodigoSenhaAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof conferirCodigoSenhaAutenticacao>>,
  TError,
  ConferirCodigoSenhaAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getConferirCodigoSenhaAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof conferirCodigoSenhaAutenticacao>>,
    ConferirCodigoSenhaAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return conferirCodigoSenhaAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ConferirCodigoSenhaAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof conferirCodigoSenhaAutenticacao>>
>;
export type ConferirCodigoSenhaAutenticacaoMutationBody = ConferenciaCodigoDto;
export type ConferirCodigoSenhaAutenticacaoMutationError = unknown;
export type ConferirCodigoSenhaAutenticacaoMutationVariables = { data: ConferenciaCodigoDto };

export const useConferirCodigoSenhaAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof conferirCodigoSenhaAutenticacao>>,
      TError,
      ConferirCodigoSenhaAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof conferirCodigoSenhaAutenticacao>>,
  TError,
  ConferirCodigoSenhaAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getConferirCodigoSenhaAutenticacaoMutationOptions(options), queryClient);
};
export const getRedefinirSenhaAutenticacaoUrl = () => {
  return `/v1/auth/senha/redefinir`;
};

export const redefinirSenhaAutenticacao = async (
  redefinicaoSenhaDto: RedefinicaoSenhaDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<SessaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<SessaoDto>(getRedefinirSenhaAutenticacaoUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(redefinicaoSenhaDto),
  });
};

export const getRedefinirSenhaAutenticacaoMutationKey = () =>
  ['redefinirSenhaAutenticacao'] as const;

export const getRedefinirSenhaAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof redefinirSenhaAutenticacao>>,
    TError,
    RedefinirSenhaAutenticacaoMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof redefinirSenhaAutenticacao>>,
  TError,
  RedefinirSenhaAutenticacaoMutationVariables,
  TContext
> => {
  const mutationKey = getRedefinirSenhaAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof redefinirSenhaAutenticacao>>,
    RedefinirSenhaAutenticacaoMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return redefinirSenhaAutenticacao(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RedefinirSenhaAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof redefinirSenhaAutenticacao>>
>;
export type RedefinirSenhaAutenticacaoMutationBody = RedefinicaoSenhaDto;
export type RedefinirSenhaAutenticacaoMutationError = unknown;
export type RedefinirSenhaAutenticacaoMutationVariables = { data: RedefinicaoSenhaDto };

export const useRedefinirSenhaAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof redefinirSenhaAutenticacao>>,
      TError,
      RedefinirSenhaAutenticacaoMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof redefinirSenhaAutenticacao>>,
  TError,
  RedefinirSenhaAutenticacaoMutationVariables,
  TContext
> => {
  return useMutation(getRedefinirSenhaAutenticacaoMutationOptions(options), queryClient);
};
export const getSairDeTodosAutenticacaoUrl = () => {
  return `/v1/auth/sair-todos`;
};

export const sairDeTodosAutenticacao = async (
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  return requisicao<void>(getSairDeTodosAutenticacaoUrl(), {
    ...options,
    method: 'POST',
  });
};

export const getSairDeTodosAutenticacaoMutationKey = () => ['sairDeTodosAutenticacao'] as const;

export const getSairDeTodosAutenticacaoMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof sairDeTodosAutenticacao>>,
    TError,
    void,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof sairDeTodosAutenticacao>>,
  TError,
  void,
  TContext
> => {
  const mutationKey = getSairDeTodosAutenticacaoMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof sairDeTodosAutenticacao>>,
    void
  > = () => {
    return sairDeTodosAutenticacao(requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SairDeTodosAutenticacaoMutationResult = NonNullable<
  Awaited<ReturnType<typeof sairDeTodosAutenticacao>>
>;

export type SairDeTodosAutenticacaoMutationError = unknown;

export const useSairDeTodosAutenticacao = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof sairDeTodosAutenticacao>>,
      TError,
      void,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof sairDeTodosAutenticacao>>,
  TError,
  void,
  TContext
> => {
  return useMutation(getSairDeTodosAutenticacaoMutationOptions(options), queryClient);
};
