/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  DefinicaoOrcamentoDto,
  ListaOrcamentosDto,
  ListarOrcamentosParams,
  OrcamentoDto,
} from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListarOrcamentosUrl = (params?: ListarOrcamentosParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/orcamentos?${stringifiedParams}` : `/v1/orcamentos`;
};

export const listarOrcamentos = async (
  params?: ListarOrcamentosParams,
  options?: Parameters<typeof requisicao>[1],
): Promise<ListaOrcamentosDto> => {
  return requisicao<ListaOrcamentosDto>(getListarOrcamentosUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getListarOrcamentosQueryKey = (params?: ListarOrcamentosParams) => {
  return [`/v1/orcamentos`, ...(params ? [params] : [])] as const;
};

export const getListarOrcamentosQueryOptions = <
  TData = Awaited<ReturnType<typeof listarOrcamentos>>,
  TError = unknown,
>(
  params?: ListarOrcamentosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarOrcamentos>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListarOrcamentosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listarOrcamentos>>> = ({ signal }) =>
    listarOrcamentos(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listarOrcamentos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListarOrcamentosQueryResult = NonNullable<Awaited<ReturnType<typeof listarOrcamentos>>>;
export type ListarOrcamentosQueryError = unknown;

export function useListarOrcamentos<
  TData = Awaited<ReturnType<typeof listarOrcamentos>>,
  TError = unknown,
>(
  params: undefined | ListarOrcamentosParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarOrcamentos>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarOrcamentos>>,
          TError,
          Awaited<ReturnType<typeof listarOrcamentos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarOrcamentos<
  TData = Awaited<ReturnType<typeof listarOrcamentos>>,
  TError = unknown,
>(
  params?: ListarOrcamentosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarOrcamentos>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarOrcamentos>>,
          TError,
          Awaited<ReturnType<typeof listarOrcamentos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarOrcamentos<
  TData = Awaited<ReturnType<typeof listarOrcamentos>>,
  TError = unknown,
>(
  params?: ListarOrcamentosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarOrcamentos>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListarOrcamentos<
  TData = Awaited<ReturnType<typeof listarOrcamentos>>,
  TError = unknown,
>(
  params?: ListarOrcamentosParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarOrcamentos>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListarOrcamentosQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getDefinirOrcamentosUrl = () => {
  return `/v1/orcamentos`;
};

export const definirOrcamentos = async (
  definicaoOrcamentoDto: DefinicaoOrcamentoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<OrcamentoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<OrcamentoDto>(getDefinirOrcamentosUrl(), {
    ...options,
    method: 'PUT',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(definicaoOrcamentoDto),
  });
};

export const getDefinirOrcamentosMutationKey = () => ['definirOrcamentos'] as const;

export const getDefinirOrcamentosMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof definirOrcamentos>>,
    TError,
    DefinirOrcamentosMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof definirOrcamentos>>,
  TError,
  DefinirOrcamentosMutationVariables,
  TContext
> => {
  const mutationKey = getDefinirOrcamentosMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof definirOrcamentos>>,
    DefinirOrcamentosMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return definirOrcamentos(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DefinirOrcamentosMutationResult = NonNullable<
  Awaited<ReturnType<typeof definirOrcamentos>>
>;
export type DefinirOrcamentosMutationBody = DefinicaoOrcamentoDto;
export type DefinirOrcamentosMutationError = unknown;
export type DefinirOrcamentosMutationVariables = { data: DefinicaoOrcamentoDto };

export const useDefinirOrcamentos = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof definirOrcamentos>>,
      TError,
      DefinirOrcamentosMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof definirOrcamentos>>,
  TError,
  DefinirOrcamentosMutationVariables,
  TContext
> => {
  return useMutation(getDefinirOrcamentosMutationOptions(options), queryClient);
};
export const getExcluirOrcamentosUrl = (id: string) => {
  return `/v1/orcamentos/${id}`;
};

export const excluirOrcamentos = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  return requisicao<void>(getExcluirOrcamentosUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getExcluirOrcamentosMutationKey = () => ['excluirOrcamentos'] as const;

export const getExcluirOrcamentosMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof excluirOrcamentos>>,
    TError,
    ExcluirOrcamentosMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof excluirOrcamentos>>,
  TError,
  ExcluirOrcamentosMutationVariables,
  TContext
> => {
  const mutationKey = getExcluirOrcamentosMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof excluirOrcamentos>>,
    ExcluirOrcamentosMutationVariables
  > = (props) => {
    const { id } = props ?? {};

    return excluirOrcamentos(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExcluirOrcamentosMutationResult = NonNullable<
  Awaited<ReturnType<typeof excluirOrcamentos>>
>;

export type ExcluirOrcamentosMutationError = unknown;
export type ExcluirOrcamentosMutationVariables = { id: string };

export const useExcluirOrcamentos = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof excluirOrcamentos>>,
      TError,
      ExcluirOrcamentosMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof excluirOrcamentos>>,
  TError,
  ExcluirOrcamentosMutationVariables,
  TContext
> => {
  return useMutation(getExcluirOrcamentosMutationOptions(options), queryClient);
};
