/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { AtualizacaoContaDtoTipo } from './atualizacaoContaDtoTipo';

export interface AtualizacaoContaDto {
  /**
   * @minLength 1
   * @maxLength 60
   */
  nome?: string;
  tipo?: AtualizacaoContaDtoTipo;
  /**
   * @minimum -100000000000
   * @maximum 100000000000
   */
  saldoInicialCentavos?: number;
}
