/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export interface AtualizacaoOnboardingDto {
  concluido?: boolean;
  etapas?: Partial<
    Record<
      'primeiro-lancamento' | 'cartoes' | 'orcamento' | 'permissoes' | 'tour',
      'concluida' | 'dispensada'
    >
  >;
  /**
   * @maxItems 50
   * @items.maxLength 80
   * @items.pattern ^[a-z0-9-]+(\.[a-z0-9-]+)*$
   */
  dicasVistas?: string[];
}
