/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type AtualizacaoContaDtoTipo =
  (typeof AtualizacaoContaDtoTipo)[keyof typeof AtualizacaoContaDtoTipo];

export const AtualizacaoContaDtoTipo = {
  corrente: 'corrente',
  poupanca: 'poupanca',
  carteira: 'carteira',
} as const;
