/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { AtualizacaoTransacaoDtoFormaPagamento } from './atualizacaoTransacaoDtoFormaPagamento';
import type { AtualizacaoTransacaoDtoStatus } from './atualizacaoTransacaoDtoStatus';
import type { AtualizacaoTransacaoDtoTipo } from './atualizacaoTransacaoDtoTipo';

export interface AtualizacaoTransacaoDto {
  tipo?: AtualizacaoTransacaoDtoTipo;
  /**
   * @minLength 1
   * @maxLength 200
   */
  descricao?: string;
  /**
   * @minimum 1
   * @maximum 100000000000
   */
  valorCentavos?: number;
  data?: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId?: string;
  formaPagamento?: AtualizacaoTransacaoDtoFormaPagamento;
  status?: AtualizacaoTransacaoDtoStatus;
  observacao?: string | null;
  contaId?: string | null;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  cartaoId?: string;
  /**
   * @maxItems 5
   * @items.pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  anexoIds?: string[];
}
