/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export interface AtualizacaoPerfilDto {
  /**
   * @minLength 1
   * @maxLength 120
   */
  nome?: string;
  /** @maxLength 30 */
  telefone?: string;
  /** @maxLength 64 */
  fusoHorario?: string;
}
