/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type AtualizacaoRecorrenciaDtoFrequencia =
  (typeof AtualizacaoRecorrenciaDtoFrequencia)[keyof typeof AtualizacaoRecorrenciaDtoFrequencia];

export const AtualizacaoRecorrenciaDtoFrequencia = {
  semanal: 'semanal',
  mensal: 'mensal',
  anual: 'anual',
} as const;
