/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { AtualizacaoCartaoDtoBandeira } from './atualizacaoCartaoDtoBandeira';

export interface AtualizacaoCartaoDto {
  /**
   * @minLength 1
   * @maxLength 60
   */
  nome?: string;
  bandeira?: AtualizacaoCartaoDtoBandeira;
  final?: string | null;
  /**
   * @minimum 1
   * @maximum 100000000000
   */
  limiteTotalCentavos?: number;
  /**
   * @minimum 1
   * @maximum 31
   */
  diaFechamento?: number;
  /**
   * @minimum 1
   * @maximum 31
   */
  diaVencimento?: number;
  /** @pattern ^#[0-9A-Fa-f]{6}$ */
  cor?: string;
  /**
   * @maxItems 5
   * @items.minimum 1
   * @items.maximum 100
   */
  faixasAlerta?: number[];
  contaPagamentoId?: string | null;
}
