/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type AtualizacaoTransacaoDtoTipo =
  (typeof AtualizacaoTransacaoDtoTipo)[keyof typeof AtualizacaoTransacaoDtoTipo];

export const AtualizacaoTransacaoDtoTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
