/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type CadastroDtoAceites = {
  /**
   * @minLength 1
   * @maxLength 40
   */
  termos: string;
  /**
   * @minLength 1
   * @maxLength 40
   */
  privacidade: string;
};
