/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { CadastroDtoAceites } from './cadastroDtoAceites';
import type { CadastroDtoDispositivo } from './cadastroDtoDispositivo';

export interface CadastroDto {
  /**
   * @minLength 1
   * @maxLength 120
   */
  nome: string;
  /**
   * @maxLength 254
   * @pattern ^(?:[A-Za-z0-9_'+\-]+\.)*[A-Za-z0-9_'+\-]*[A-Za-z0-9_+-]@(?:[A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
   */
  email: string;
  /** @maxLength 30 */
  telefone: string;
  /**
   * @minLength 8
   * @maxLength 128
   */
  senha: string;
  aceites: CadastroDtoAceites;
  dispositivo: CadastroDtoDispositivo;
}
