/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { CadastroDtoDispositivoPlataforma } from './cadastroDtoDispositivoPlataforma';

export type CadastroDtoDispositivo = {
  /**
   * @minLength 8
   * @maxLength 200
   */
  identificador: string;
  plataforma: CadastroDtoDispositivoPlataforma;
  /** @maxLength 100 */
  modelo?: string;
};
