/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type CategoriaDtoTipo = (typeof CategoriaDtoTipo)[keyof typeof CategoriaDtoTipo];

export const CategoriaDtoTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
