/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ConfigAppDtoVersaoMinima = {
  /** @pattern ^\d{1,4}\.\d{1,4}\.\d{1,4}$ */
  ios: string;
  /** @pattern ^\d{1,4}\.\d{1,4}\.\d{1,4}$ */
  android: string;
};
