/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { ConfigAppDtoFlags } from './configAppDtoFlags';
import type { ConfigAppDtoVersaoMinima } from './configAppDtoVersaoMinima';

export interface ConfigAppDto {
  versaoMinima: ConfigAppDtoVersaoMinima;
  flags: ConfigAppDtoFlags;
  sugestoesChat: string[];
}
