/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { ContaDtoOrigem } from './contaDtoOrigem';
import type { ContaDtoTipo } from './contaDtoTipo';

export interface ContaDto {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  nome: string;
  tipo: ContaDtoTipo;
  origem: ContaDtoOrigem;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  saldoInicialCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  saldoAtualCentavos: number;
}
