/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ContaDtoTipo = (typeof ContaDtoTipo)[keyof typeof ContaDtoTipo];

export const ContaDtoTipo = {
  corrente: 'corrente',
  poupanca: 'poupanca',
  carteira: 'carteira',
} as const;
