/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { DashboardDtoOrcamentosItensItem } from './dashboardDtoOrcamentosItensItem';
import type { DashboardDtoOrcamentosTotais } from './dashboardDtoOrcamentosTotais';

export type DashboardDtoOrcamentos = {
  competencia: string;
  itens: DashboardDtoOrcamentosItensItem[];
  totais: DashboardDtoOrcamentosTotais;
};
