/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { DashboardDtoCartoesItemFaturaAtual } from './dashboardDtoCartoesItemFaturaAtual';
import type { DashboardDtoCartoesItemOrigem } from './dashboardDtoCartoesItemOrigem';

export type DashboardDtoCartoesItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  nome: string;
  /** @nullable */
  bandeira: string | null;
  /** @nullable */
  final: string | null;
  cor: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  diaFechamento: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  diaVencimento: number;
  /**
   * @items.minimum -9007199254740991
   * @items.maximum 9007199254740991
   */
  faixasAlerta: number[];
  origem: DashboardDtoCartoesItemOrigem;
  contaPagamentoId: string | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  limiteTotalCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  limiteUsadoCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  limiteDisponivelCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  percentualUsado: number;
  faturaAtual: DashboardDtoCartoesItemFaturaAtual;
};
