/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { DashboardDtoPeriodoTipo } from './dashboardDtoPeriodoTipo';

export type DashboardDtoPeriodo = {
  tipo: DashboardDtoPeriodoTipo;
  de: string;
  ate: string;
};
