/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { DashboardDtoCartoesItem } from './dashboardDtoCartoesItem';
import type { DashboardDtoOnboarding } from './dashboardDtoOnboarding';
import type { DashboardDtoOrcamentos } from './dashboardDtoOrcamentos';
import type { DashboardDtoPeriodo } from './dashboardDtoPeriodo';
import type { DashboardDtoProximosVencimentosItem } from './dashboardDtoProximosVencimentosItem';
import type { DashboardDtoResumo } from './dashboardDtoResumo';

export interface DashboardDto {
  periodo: DashboardDtoPeriodo;
  resumo: DashboardDtoResumo;
  proximosVencimentos: DashboardDtoProximosVencimentosItem[];
  cartoes: DashboardDtoCartoesItem[];
  orcamentos: DashboardDtoOrcamentos;
  onboarding: DashboardDtoOnboarding;
}
