/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DashboardDtoProximosVencimentosItemTipo =
  (typeof DashboardDtoProximosVencimentosItemTipo)[keyof typeof DashboardDtoProximosVencimentosItemTipo];

export const DashboardDtoProximosVencimentosItemTipo = {
  fatura: 'fatura',
  parcela: 'parcela',
  conta: 'conta',
} as const;
