/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DashboardDtoResumo = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  saldoCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  receitasCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  receitasPagasCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  despesasPagasCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  despesasPendentesCentavos: number;
};
