/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DashboardDtoPeriodoTipo =
  (typeof DashboardDtoPeriodoTipo)[keyof typeof DashboardDtoPeriodoTipo];

export const DashboardDtoPeriodoTipo = {
  mes_atual: 'mes_atual',
  mes_anterior: 'mes_anterior',
  personalizado: 'personalizado',
} as const;
