/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DashboardDtoOrcamentosItensItemFaixa =
  (typeof DashboardDtoOrcamentosItensItemFaixa)[keyof typeof DashboardDtoOrcamentosItensItemFaixa];

export const DashboardDtoOrcamentosItensItemFaixa = {
  normal: 'normal',
  atencao: 'atencao',
  estourado: 'estourado',
} as const;
