/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DashboardDtoOnboardingEtapasItemEtapa =
  (typeof DashboardDtoOnboardingEtapasItemEtapa)[keyof typeof DashboardDtoOnboardingEtapasItemEtapa];

export const DashboardDtoOnboardingEtapasItemEtapa = {
  'primeiro-lancamento': 'primeiro-lancamento',
  cartoes: 'cartoes',
  orcamento: 'orcamento',
  permissoes: 'permissoes',
  tour: 'tour',
} as const;
