/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { DashboardDtoOnboardingEtapasItem } from './dashboardDtoOnboardingEtapasItem';

export type DashboardDtoOnboarding = {
  concluido: boolean;
  etapas: DashboardDtoOnboardingEtapasItem[];
  checklistVisivel: boolean;
  dicasVistas: string[];
};
