/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DashboardDtoCartoesItemOrigem =
  (typeof DashboardDtoCartoesItemOrigem)[keyof typeof DashboardDtoCartoesItemOrigem];

export const DashboardDtoCartoesItemOrigem = {
  manual: 'manual',
  open_finance: 'open_finance',
} as const;
