/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { DashboardDtoOnboardingEtapasItemEtapa } from './dashboardDtoOnboardingEtapasItemEtapa';
import type { DashboardDtoOnboardingEtapasItemSituacao } from './dashboardDtoOnboardingEtapasItemSituacao';

export type DashboardDtoOnboardingEtapasItem = {
  etapa: DashboardDtoOnboardingEtapasItemEtapa;
  situacao: DashboardDtoOnboardingEtapasItemSituacao;
  em: string | null;
};
