/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DetalheFaturaDtoTransacoesItemOrigem =
  (typeof DetalheFaturaDtoTransacoesItemOrigem)[keyof typeof DetalheFaturaDtoTransacoesItemOrigem];

export const DetalheFaturaDtoTransacoesItemOrigem = {
  manual: 'manual',
  mony: 'mony',
  open_finance: 'open_finance',
  foto: 'foto',
} as const;
