/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DetalheFaturaDtoTransacoesItemNatureza =
  (typeof DetalheFaturaDtoTransacoesItemNatureza)[keyof typeof DetalheFaturaDtoTransacoesItemNatureza];

export const DetalheFaturaDtoTransacoesItemNatureza = {
  normal: 'normal',
  pagamento_fatura: 'pagamento_fatura',
  transferencia: 'transferencia',
} as const;
