/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DetalheFaturaDtoPagamentosItemAnexosItemTipo =
  (typeof DetalheFaturaDtoPagamentosItemAnexosItemTipo)[keyof typeof DetalheFaturaDtoPagamentosItemAnexosItemTipo];

export const DetalheFaturaDtoPagamentosItemAnexosItemTipo = {
  foto: 'foto',
  pdf: 'pdf',
  comprovante: 'comprovante',
} as const;
