/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DetalheParcelamentoDtoTipo =
  (typeof DetalheParcelamentoDtoTipo)[keyof typeof DetalheParcelamentoDtoTipo];

export const DetalheParcelamentoDtoTipo = {
  compra_cartao: 'compra_cartao',
  divida: 'divida',
} as const;
