/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DetalheParcelamentoDtoProgresso = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  parcelasPagas: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  parcelas: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorPagoCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorRestanteCentavos: number;
};
