/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DetalheFaturaDtoTransacoesItemTipo =
  (typeof DetalheFaturaDtoTransacoesItemTipo)[keyof typeof DetalheFaturaDtoTransacoesItemTipo];

export const DetalheFaturaDtoTransacoesItemTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
