/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DetalheParcelamentoDtoStatus =
  (typeof DetalheParcelamentoDtoStatus)[keyof typeof DetalheParcelamentoDtoStatus];

export const DetalheParcelamentoDtoStatus = {
  ativa: 'ativa',
  quitada: 'quitada',
  atrasada: 'atrasada',
  cancelada: 'cancelada',
} as const;
