/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DetalheParcelamentoDtoProximaParcelaStatus =
  (typeof DetalheParcelamentoDtoProximaParcelaStatus)[keyof typeof DetalheParcelamentoDtoProximaParcelaStatus];

export const DetalheParcelamentoDtoProximaParcelaStatus = {
  pendente: 'pendente',
  pago: 'pago',
  atrasado: 'atrasado',
} as const;
