/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { DetalheFaturaDtoCartao } from './detalheFaturaDtoCartao';
import type { DetalheFaturaDtoFatura } from './detalheFaturaDtoFatura';
import type { DetalheFaturaDtoPagamentosItem } from './detalheFaturaDtoPagamentosItem';
import type { DetalheFaturaDtoTransacoesItem } from './detalheFaturaDtoTransacoesItem';

export interface DetalheFaturaDto {
  fatura: DetalheFaturaDtoFatura;
  cartao: DetalheFaturaDtoCartao;
  transacoes: DetalheFaturaDtoTransacoesItem[];
  pagamentos: DetalheFaturaDtoPagamentosItem[];
}
