/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DetalheFaturaDtoPagamentosItemNatureza =
  (typeof DetalheFaturaDtoPagamentosItemNatureza)[keyof typeof DetalheFaturaDtoPagamentosItemNatureza];

export const DetalheFaturaDtoPagamentosItemNatureza = {
  normal: 'normal',
  pagamento_fatura: 'pagamento_fatura',
  transferencia: 'transferencia',
} as const;
