/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DetalheFaturaDtoTransacoesItemStatus =
  (typeof DetalheFaturaDtoTransacoesItemStatus)[keyof typeof DetalheFaturaDtoTransacoesItemStatus];

export const DetalheFaturaDtoTransacoesItemStatus = {
  pago: 'pago',
  pendente: 'pendente',
} as const;
