/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { DetalheParcelamentoDtoParcelasItem } from './detalheParcelamentoDtoParcelasItem';
import type { DetalheParcelamentoDtoProgresso } from './detalheParcelamentoDtoProgresso';
import type { DetalheParcelamentoDtoProximaParcela } from './detalheParcelamentoDtoProximaParcela';
import type { DetalheParcelamentoDtoStatus } from './detalheParcelamentoDtoStatus';
import type { DetalheParcelamentoDtoTipo } from './detalheParcelamentoDtoTipo';

export interface DetalheParcelamentoDto {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  nome: string;
  tipo: DetalheParcelamentoDtoTipo;
  status: DetalheParcelamentoDtoStatus;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorTotalCentavos: number;
  valorFinanciadoCentavos: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  totalParcelas: number;
  taxaJurosMensal: number[];
  dataInicio: string;
  observacao: string[];
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  cartaoId: string | null;
  progresso: DetalheParcelamentoDtoProgresso;
  proximaParcela: DetalheParcelamentoDtoProximaParcela;
  parcelas: DetalheParcelamentoDtoParcelasItem[];
}
