/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type DetalheParcelamentoDtoParcelasItemStatus =
  (typeof DetalheParcelamentoDtoParcelasItemStatus)[keyof typeof DetalheParcelamentoDtoParcelasItemStatus];

export const DetalheParcelamentoDtoParcelasItemStatus = {
  pendente: 'pendente',
  pago: 'pago',
  atrasado: 'atrasado',
} as const;
