/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ExcluirTransacoesRecorrencia =
  (typeof ExcluirTransacoesRecorrencia)[keyof typeof ExcluirTransacoesRecorrencia];

export const ExcluirTransacoesRecorrencia = {
  esta: 'esta',
  proximas: 'proximas',
  todas: 'todas',
} as const;
