/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type LeituraArquivoDtoTipo =
  (typeof LeituraArquivoDtoTipo)[keyof typeof LeituraArquivoDtoTipo];

export const LeituraArquivoDtoTipo = {
  foto: 'foto',
  pdf: 'pdf',
  comprovante: 'comprovante',
} as const;
