/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { ListaOrcamentosDtoItensItem } from './listaOrcamentosDtoItensItem';
import type { ListaOrcamentosDtoTotais } from './listaOrcamentosDtoTotais';

export interface ListaOrcamentosDto {
  competencia: string;
  itens: ListaOrcamentosDtoItensItem[];
  totais: ListaOrcamentosDtoTotais;
}
