/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ListaContasDtoItensItemTipo =
  (typeof ListaContasDtoItensItemTipo)[keyof typeof ListaContasDtoItensItemTipo];

export const ListaContasDtoItensItemTipo = {
  corrente: 'corrente',
  poupanca: 'poupanca',
  carteira: 'carteira',
} as const;
