/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ListaRecorrenciasDtoItensItemFrequencia =
  (typeof ListaRecorrenciasDtoItensItemFrequencia)[keyof typeof ListaRecorrenciasDtoItensItemFrequencia];

export const ListaRecorrenciasDtoItensItemFrequencia = {
  semanal: 'semanal',
  mensal: 'mensal',
  anual: 'anual',
} as const;
