/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { ListarTransacoesFormaPagamento } from './listarTransacoesFormaPagamento';
import type { ListarTransacoesOrigem } from './listarTransacoesOrigem';
import type { ListarTransacoesStatus } from './listarTransacoesStatus';
import type { ListarTransacoesTipo } from './listarTransacoesTipo';

export type ListarTransacoesParams = {
  de?: string;
  ate?: string;
  tipo?: ListarTransacoesTipo;
  /**
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  categoriaId?: string;
  formaPagamento?: ListarTransacoesFormaPagamento;
  /**
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  cartaoId?: string;
  /**
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  contaId?: string;
  status?: ListarTransacoesStatus;
  origem?: ListarTransacoesOrigem;
  /**
   * @minLength 1
   * @maxLength 100
   */
  texto?: string;
  /**
   * @maxLength 200
   */
  cursor?: string;
  /**
   * @minimum 1
   * @maximum 100
   */
  limite?: number;
};
