/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ListaParcelamentosDtoItensItemProximaParcelaStatus =
  (typeof ListaParcelamentosDtoItensItemProximaParcelaStatus)[keyof typeof ListaParcelamentosDtoItensItemProximaParcelaStatus];

export const ListaParcelamentosDtoItensItemProximaParcelaStatus = {
  pendente: 'pendente',
  pago: 'pago',
  atrasado: 'atrasado',
} as const;
