/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ListaOrcamentosDtoItensItemFaixa =
  (typeof ListaOrcamentosDtoItensItemFaixa)[keyof typeof ListaOrcamentosDtoItensItemFaixa];

export const ListaOrcamentosDtoItensItemFaixa = {
  normal: 'normal',
  atencao: 'atencao',
  estourado: 'estourado',
} as const;
