/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { ListarParcelamentosStatus } from './listarParcelamentosStatus';
import type { ListarParcelamentosTipo } from './listarParcelamentosTipo';

export type ListarParcelamentosParams = {
  tipo?: ListarParcelamentosTipo;
  status?: ListarParcelamentosStatus;
};
