/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { ListaOrcamentosDtoItensItemFaixa } from './listaOrcamentosDtoItensItemFaixa';

export type ListaOrcamentosDtoItensItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  competencia: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorLimiteCentavos: number;
  repetirMensal: boolean;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  gastoCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  restanteCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  percentualUsado: number;
  faixa: ListaOrcamentosDtoItensItemFaixa;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  projecaoCentavos: number;
};
