/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { ListaCartoesDtoItensItemFaturaAtualStatus } from './listaCartoesDtoItensItemFaturaAtualStatus';

export type ListaCartoesDtoItensItemFaturaAtual = {
  id: string | null;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  cartaoId: string;
  competencia: string;
  dataFechamento: string;
  dataVencimento: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorTotalCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorPagoCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  saldoCentavos: number;
  status: ListaCartoesDtoItensItemFaturaAtualStatus;
  venceNoFimDeSemana: boolean;
};
