/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { ListaContasDtoItensItem } from './listaContasDtoItensItem';

export interface ListaContasDto {
  itens: ListaContasDtoItensItem[];
}
