/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ListaCartoesDtoItensItemOrigem =
  (typeof ListaCartoesDtoItensItemOrigem)[keyof typeof ListaCartoesDtoItensItemOrigem];

export const ListaCartoesDtoItensItemOrigem = {
  manual: 'manual',
  open_finance: 'open_finance',
} as const;
