/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ListarParcelamentosTipo =
  (typeof ListarParcelamentosTipo)[keyof typeof ListarParcelamentosTipo];

export const ListarParcelamentosTipo = {
  compra_cartao: 'compra_cartao',
  divida: 'divida',
} as const;
