/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ListarTransacoesStatus =
  (typeof ListarTransacoesStatus)[keyof typeof ListarTransacoesStatus];

export const ListarTransacoesStatus = {
  pago: 'pago',
  pendente: 'pendente',
} as const;
