/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ListarTransacoesTipo = (typeof ListarTransacoesTipo)[keyof typeof ListarTransacoesTipo];

export const ListarTransacoesTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
