/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { ListaCartoesDtoItensItem } from './listaCartoesDtoItensItem';

export interface ListaCartoesDto {
  itens: ListaCartoesDtoItensItem[];
}
