/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ListaRecorrenciasDtoItensItemTipo =
  (typeof ListaRecorrenciasDtoItensItemTipo)[keyof typeof ListaRecorrenciasDtoItensItemTipo];

export const ListaRecorrenciasDtoItensItemTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
