/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ListaParcelamentosDtoItensItemStatus =
  (typeof ListaParcelamentosDtoItensItemStatus)[keyof typeof ListaParcelamentosDtoItensItemStatus];

export const ListaParcelamentosDtoItensItemStatus = {
  ativa: 'ativa',
  quitada: 'quitada',
  atrasada: 'atrasada',
  cancelada: 'cancelada',
} as const;
