/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type LoginDtoDispositivoPlataforma =
  (typeof LoginDtoDispositivoPlataforma)[keyof typeof LoginDtoDispositivoPlataforma];

export const LoginDtoDispositivoPlataforma = {
  ios: 'ios',
  android: 'android',
} as const;
