/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type LoginSocialDtoProvedor =
  (typeof LoginSocialDtoProvedor)[keyof typeof LoginSocialDtoProvedor];

export const LoginSocialDtoProvedor = {
  google: 'google',
  apple: 'apple',
} as const;
