/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type LoginSocialDtoDispositivoPlataforma =
  (typeof LoginSocialDtoDispositivoPlataforma)[keyof typeof LoginSocialDtoDispositivoPlataforma];

export const LoginSocialDtoDispositivoPlataforma = {
  ios: 'ios',
  android: 'android',
} as const;
