/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { LoginSocialDtoAceites } from './loginSocialDtoAceites';
import type { LoginSocialDtoDispositivo } from './loginSocialDtoDispositivo';
import type { LoginSocialDtoProvedor } from './loginSocialDtoProvedor';

export interface LoginSocialDto {
  provedor: LoginSocialDtoProvedor;
  /**
   * @minLength 20
   * @maxLength 8000
   */
  idToken: string;
  /**
   * @minLength 16
   * @maxLength 200
   */
  nonce?: string;
  /**
   * @minLength 1
   * @maxLength 120
   */
  nome?: string;
  /** @maxLength 30 */
  telefone?: string;
  aceites?: LoginSocialDtoAceites;
  dispositivo: LoginSocialDtoDispositivo;
}
