/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type LoteTransacoesDtoAcao =
  (typeof LoteTransacoesDtoAcao)[keyof typeof LoteTransacoesDtoAcao];

export const LoteTransacoesDtoAcao = {
  excluir: 'excluir',
  mudar_categoria: 'mudar_categoria',
} as const;
