/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type NovaTransacaoDtoTipo = (typeof NovaTransacaoDtoTipo)[keyof typeof NovaTransacaoDtoTipo];

export const NovaTransacaoDtoTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
