/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export interface NovaMetaDto {
  /**
   * @minLength 1
   * @maxLength 100
   */
  titulo: string;
  /**
   * @minimum 1
   * @maximum 100000000000
   */
  valorAlvoCentavos: number;
  prazo?: string;
}
