/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { NovaTransacaoDtoFormaPagamento } from './novaTransacaoDtoFormaPagamento';
import type { NovaTransacaoDtoStatus } from './novaTransacaoDtoStatus';
import type { NovaTransacaoDtoTipo } from './novaTransacaoDtoTipo';

export interface NovaTransacaoDto {
  tipo: NovaTransacaoDtoTipo;
  /**
   * @minLength 1
   * @maxLength 200
   */
  descricao: string;
  /**
   * @minimum 1
   * @maximum 100000000000
   */
  valorCentavos: number;
  data?: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  formaPagamento?: NovaTransacaoDtoFormaPagamento;
  status?: NovaTransacaoDtoStatus;
  /** @maxLength 1000 */
  observacao?: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  contaId?: string;
  /**
   * @maxItems 5
   * @items.pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  anexoIds?: string[];
}
