/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { NovaCategoriaDtoTipo } from './novaCategoriaDtoTipo';

export interface NovaCategoriaDto {
  /**
   * @minLength 1
   * @maxLength 40
   */
  nome: string;
  tipo: NovaCategoriaDtoTipo;
  /** @pattern ^#[0-9A-Fa-f]{6}$ */
  cor: string;
  /**
   * @maxLength 40
   * @pattern ^[a-z0-9]+(-[a-z0-9]+)*$
   */
  icone: string;
}
