/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type NovaContaDtoTipo = (typeof NovaContaDtoTipo)[keyof typeof NovaContaDtoTipo];

export const NovaContaDtoTipo = {
  corrente: 'corrente',
  poupanca: 'poupanca',
  carteira: 'carteira',
} as const;
