/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { NovaRecorrenciaDtoFormaPagamento } from './novaRecorrenciaDtoFormaPagamento';
import type { NovaRecorrenciaDtoFrequencia } from './novaRecorrenciaDtoFrequencia';
import type { NovaRecorrenciaDtoTipo } from './novaRecorrenciaDtoTipo';

export interface NovaRecorrenciaDto {
  tipo: NovaRecorrenciaDtoTipo;
  /**
   * @minLength 1
   * @maxLength 200
   */
  descricao: string;
  /**
   * @minimum 1
   * @maximum 100000000000
   */
  valorCentavos: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  formaPagamento?: NovaRecorrenciaDtoFormaPagamento;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  contaId?: string;
  frequencia: NovaRecorrenciaDtoFrequencia;
  /**
   * @minimum 0
   * @maximum 31
   */
  dia?: number;
  dataInicio: string;
  dataFim?: string;
}
