/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type NovaCategoriaDtoTipo = (typeof NovaCategoriaDtoTipo)[keyof typeof NovaCategoriaDtoTipo];

export const NovaCategoriaDtoTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
