/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export interface NovoAporteDto {
  /**
   * @minimum 1
   * @maximum 100000000000
   */
  valorCentavos: number;
  data?: string;
}
