/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { NovoArquivoDtoTipo } from './novoArquivoDtoTipo';
import type { NovoArquivoDtoTipoConteudo } from './novoArquivoDtoTipoConteudo';

export interface NovoArquivoDto {
  tipo: NovoArquivoDtoTipo;
  tipoConteudo: NovoArquivoDtoTipoConteudo;
  /**
   * @minimum 1
   * @maximum 10485760
   */
  tamanho: number;
}
