/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type NovoCartaoDtoBandeira =
  (typeof NovoCartaoDtoBandeira)[keyof typeof NovoCartaoDtoBandeira];

export const NovoCartaoDtoBandeira = {
  visa: 'visa',
  mastercard: 'mastercard',
  elo: 'elo',
  amex: 'amex',
  hipercard: 'hipercard',
  diners: 'diners',
  outra: 'outra',
} as const;
