/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { NovoParcelamentoDtoFormaPagamento } from './novoParcelamentoDtoFormaPagamento';
import type { NovoParcelamentoDtoTipo } from './novoParcelamentoDtoTipo';

export interface NovoParcelamentoDto {
  tipo: NovoParcelamentoDtoTipo;
  /**
   * @minLength 1
   * @maxLength 100
   */
  nome: string;
  /**
   * @minimum 1
   * @maximum 100000000000
   */
  valorCentavos: number;
  /**
   * @minimum 2
   * @maximum 480
   */
  totalParcelas: number;
  /**
   * @minimum 0
   * @maximum 100
   */
  taxaJurosMensal?: number;
  dataInicio?: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  /** @maxLength 1000 */
  observacao?: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  cartaoId?: string;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  contaId?: string;
  formaPagamento?: NovoParcelamentoDtoFormaPagamento;
}
