/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { NovoCartaoDtoBandeira } from './novoCartaoDtoBandeira';

export interface NovoCartaoDto {
  /**
   * @minLength 1
   * @maxLength 60
   */
  nome: string;
  bandeira?: NovoCartaoDtoBandeira;
  /** @pattern ^\d{4}$ */
  final?: string;
  /**
   * @minimum 1
   * @maximum 100000000000
   */
  limiteTotalCentavos: number;
  /**
   * @minimum 1
   * @maximum 31
   */
  diaFechamento: number;
  /**
   * @minimum 1
   * @maximum 31
   */
  diaVencimento: number;
  /** @pattern ^#[0-9A-Fa-f]{6}$ */
  cor: string;
  /**
   * @maxItems 5
   * @items.minimum 1
   * @items.maximum 100
   */
  faixasAlerta?: number[];
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  contaPagamentoId?: string;
}
