/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type NovoArquivoDtoTipoConteudo =
  (typeof NovoArquivoDtoTipoConteudo)[keyof typeof NovoArquivoDtoTipoConteudo];

export const NovoArquivoDtoTipoConteudo = {
  'image/jpeg': 'image/jpeg',
  'image/png': 'image/png',
  'image/heic': 'image/heic',
  'image/webp': 'image/webp',
  'application/pdf': 'application/pdf',
} as const;
