/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type NovoArquivoDtoTipo = (typeof NovoArquivoDtoTipo)[keyof typeof NovoArquivoDtoTipo];

export const NovoArquivoDtoTipo = {
  foto: 'foto',
  pdf: 'pdf',
  comprovante: 'comprovante',
} as const;
