/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type NovoParcelamentoDtoTipo =
  (typeof NovoParcelamentoDtoTipo)[keyof typeof NovoParcelamentoDtoTipo];

export const NovoParcelamentoDtoTipo = {
  compra_cartao: 'compra_cartao',
  divida: 'divida',
} as const;
