/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type OnboardingDtoEtapasItemEtapa =
  (typeof OnboardingDtoEtapasItemEtapa)[keyof typeof OnboardingDtoEtapasItemEtapa];

export const OnboardingDtoEtapasItemEtapa = {
  'primeiro-lancamento': 'primeiro-lancamento',
  cartoes: 'cartoes',
  orcamento: 'orcamento',
  permissoes: 'permissoes',
  tour: 'tour',
} as const;
