/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { OnboardingDtoEtapasItem } from './onboardingDtoEtapasItem';

export interface OnboardingDto {
  concluido: boolean;
  etapas: OnboardingDtoEtapasItem[];
  checklistVisivel: boolean;
  dicasVistas: string[];
}
