/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { OnboardingDtoEtapasItemEtapa } from './onboardingDtoEtapasItemEtapa';
import type { OnboardingDtoEtapasItemSituacao } from './onboardingDtoEtapasItemSituacao';

export type OnboardingDtoEtapasItem = {
  etapa: OnboardingDtoEtapasItemEtapa;
  situacao: OnboardingDtoEtapasItemSituacao;
  em: string | null;
};
