/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type OrcamentoDtoFaixa = (typeof OrcamentoDtoFaixa)[keyof typeof OrcamentoDtoFaixa];

export const OrcamentoDtoFaixa = {
  normal: 'normal',
  atencao: 'atencao',
  estourado: 'estourado',
} as const;
