/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type PagamentoFaturaDtoFormaPagamento =
  (typeof PagamentoFaturaDtoFormaPagamento)[keyof typeof PagamentoFaturaDtoFormaPagamento];

export const PagamentoFaturaDtoFormaPagamento = {
  pix: 'pix',
  debito: 'debito',
  dinheiro: 'dinheiro',
  boleto: 'boleto',
} as const;
