/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type PaginaTransacoesDtoItensItemTipo =
  (typeof PaginaTransacoesDtoItensItemTipo)[keyof typeof PaginaTransacoesDtoItensItemTipo];

export const PaginaTransacoesDtoItensItemTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
