/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type PaginaTransacoesDtoItensItemAnexosItemTipo =
  (typeof PaginaTransacoesDtoItensItemAnexosItemTipo)[keyof typeof PaginaTransacoesDtoItensItemAnexosItemTipo];

export const PaginaTransacoesDtoItensItemAnexosItemTipo = {
  foto: 'foto',
  pdf: 'pdf',
  comprovante: 'comprovante',
} as const;
