/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { PaginaTransacoesDtoItensItem } from './paginaTransacoesDtoItensItem';

export interface PaginaTransacoesDto {
  itens: PaginaTransacoesDtoItensItem[];
  proximoCursor: string[];
}
