/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { PaginaTransacoesDtoItensItemAnexosItem } from './paginaTransacoesDtoItensItemAnexosItem';
import type { PaginaTransacoesDtoItensItemFormaPagamento } from './paginaTransacoesDtoItensItemFormaPagamento';
import type { PaginaTransacoesDtoItensItemNatureza } from './paginaTransacoesDtoItensItemNatureza';
import type { PaginaTransacoesDtoItensItemOrigem } from './paginaTransacoesDtoItensItemOrigem';
import type { PaginaTransacoesDtoItensItemStatus } from './paginaTransacoesDtoItensItemStatus';
import type { PaginaTransacoesDtoItensItemTipo } from './paginaTransacoesDtoItensItemTipo';

export type PaginaTransacoesDtoItensItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  tipo: PaginaTransacoesDtoItensItemTipo;
  descricao: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorCentavos: number;
  data: string;
  status: PaginaTransacoesDtoItensItemStatus;
  formaPagamento: PaginaTransacoesDtoItensItemFormaPagamento;
  origem: PaginaTransacoesDtoItensItemOrigem;
  natureza: PaginaTransacoesDtoItensItemNatureza;
  /** @nullable */
  observacao: string | null;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  contaId: string | null;
  cartaoId: string | null;
  faturaId: string | null;
  recorrenciaId: string | null;
  parcelamentoId: string | null;
  anexos: PaginaTransacoesDtoItensItemAnexosItem[];
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  criadoEm: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  atualizadoEm: string;
};
