/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type PaginaTransacoesDtoItensItemOrigem =
  (typeof PaginaTransacoesDtoItensItemOrigem)[keyof typeof PaginaTransacoesDtoItensItemOrigem];

export const PaginaTransacoesDtoItensItemOrigem = {
  manual: 'manual',
  mony: 'mony',
  open_finance: 'open_finance',
  foto: 'foto',
} as const;
