/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type PerfilDtoLoginsSociaisItem =
  (typeof PerfilDtoLoginsSociaisItem)[keyof typeof PerfilDtoLoginsSociaisItem];

export const PerfilDtoLoginsSociaisItem = {
  google: 'google',
  apple: 'apple',
} as const;
