/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RecorrenciaDtoFrequencia =
  (typeof RecorrenciaDtoFrequencia)[keyof typeof RecorrenciaDtoFrequencia];

export const RecorrenciaDtoFrequencia = {
  semanal: 'semanal',
  mensal: 'mensal',
  anual: 'anual',
} as const;
