/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RecorrenciaDtoFormaPagamento } from './recorrenciaDtoFormaPagamento';
import type { RecorrenciaDtoFrequencia } from './recorrenciaDtoFrequencia';
import type { RecorrenciaDtoTipo } from './recorrenciaDtoTipo';

export interface RecorrenciaDto {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  tipo: RecorrenciaDtoTipo;
  descricao: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorCentavos: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  formaPagamento: RecorrenciaDtoFormaPagamento;
  contaId: string | null;
  frequencia: RecorrenciaDtoFrequencia;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  dia: number;
  dataInicio: string;
  dataFim: string[];
  proximaGeracao: string[];
  ativa: boolean;
}
