/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RecorrenciaDtoTipo = (typeof RecorrenciaDtoTipo)[keyof typeof RecorrenciaDtoTipo];

export const RecorrenciaDtoTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
