/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RecorrenciaDtoFormaPagamento =
  (typeof RecorrenciaDtoFormaPagamento)[keyof typeof RecorrenciaDtoFormaPagamento] | null;

export const RecorrenciaDtoFormaPagamento = {
  cartao_credito: 'cartao_credito',
  pix: 'pix',
  debito: 'debito',
  dinheiro: 'dinheiro',
  boleto: 'boleto',
} as const;
