/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RedefinicaoSenhaDtoDispositivoPlataforma =
  (typeof RedefinicaoSenhaDtoDispositivoPlataforma)[keyof typeof RedefinicaoSenhaDtoDispositivoPlataforma];

export const RedefinicaoSenhaDtoDispositivoPlataforma = {
  ios: 'ios',
  android: 'android',
} as const;
