/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaPagamentoFaturaDtoTransacaoAnexosItemTipo =
  (typeof RespostaPagamentoFaturaDtoTransacaoAnexosItemTipo)[keyof typeof RespostaPagamentoFaturaDtoTransacaoAnexosItemTipo];

export const RespostaPagamentoFaturaDtoTransacaoAnexosItemTipo = {
  foto: 'foto',
  pdf: 'pdf',
  comprovante: 'comprovante',
} as const;
