/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaTransacaoDtoTransacaoNatureza =
  (typeof RespostaTransacaoDtoTransacaoNatureza)[keyof typeof RespostaTransacaoDtoTransacaoNatureza];

export const RespostaTransacaoDtoTransacaoNatureza = {
  normal: 'normal',
  pagamento_fatura: 'pagamento_fatura',
  transferencia: 'transferencia',
} as const;
