/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaRecorrenciaDtoRecorrenciaFrequencia =
  (typeof RespostaRecorrenciaDtoRecorrenciaFrequencia)[keyof typeof RespostaRecorrenciaDtoRecorrenciaFrequencia];

export const RespostaRecorrenciaDtoRecorrenciaFrequencia = {
  semanal: 'semanal',
  mensal: 'mensal',
  anual: 'anual',
} as const;
