/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaParcelamentoDtoImpacto } from './respostaParcelamentoDtoImpacto';
import type { RespostaParcelamentoDtoParcelamento } from './respostaParcelamentoDtoParcelamento';

export interface RespostaParcelamentoDto {
  parcelamento: RespostaParcelamentoDtoParcelamento;
  impacto: RespostaParcelamentoDtoImpacto;
}
