/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaPagamentoFaturaDtoFaturaStatus =
  (typeof RespostaPagamentoFaturaDtoFaturaStatus)[keyof typeof RespostaPagamentoFaturaDtoFaturaStatus];

export const RespostaPagamentoFaturaDtoFaturaStatus = {
  aberta: 'aberta',
  fechada: 'fechada',
  paga: 'paga',
  parcial: 'parcial',
  atrasada: 'atrasada',
} as const;
