/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaTransacaoDtoTransacaoFormaPagamento =
  | (typeof RespostaTransacaoDtoTransacaoFormaPagamento)[keyof typeof RespostaTransacaoDtoTransacaoFormaPagamento]
  | null;

export const RespostaTransacaoDtoTransacaoFormaPagamento = {
  cartao_credito: 'cartao_credito',
  pix: 'pix',
  debito: 'debito',
  dinheiro: 'dinheiro',
  boleto: 'boleto',
} as const;
