/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaAporteDtoAporte } from './respostaAporteDtoAporte';
import type { RespostaAporteDtoMeta } from './respostaAporteDtoMeta';

export interface RespostaAporteDto {
  meta: RespostaAporteDtoMeta;
  aporte: RespostaAporteDtoAporte;
  sugerirConclusao: boolean;
}
