/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaParcelaDtoParcelamentoProximaParcelaStatus =
  (typeof RespostaParcelaDtoParcelamentoProximaParcelaStatus)[keyof typeof RespostaParcelaDtoParcelamentoProximaParcelaStatus];

export const RespostaParcelaDtoParcelamentoProximaParcelaStatus = {
  pendente: 'pendente',
  pago: 'pago',
  atrasado: 'atrasado',
} as const;
