/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaTransacaoDtoTransacaoStatus =
  (typeof RespostaTransacaoDtoTransacaoStatus)[keyof typeof RespostaTransacaoDtoTransacaoStatus];

export const RespostaTransacaoDtoTransacaoStatus = {
  pago: 'pago',
  pendente: 'pendente',
} as const;
