/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaParcelamentoDtoParcelamentoParcelasItemStatus =
  (typeof RespostaParcelamentoDtoParcelamentoParcelasItemStatus)[keyof typeof RespostaParcelamentoDtoParcelamentoParcelasItemStatus];

export const RespostaParcelamentoDtoParcelamentoParcelasItemStatus = {
  pendente: 'pendente',
  pago: 'pago',
  atrasado: 'atrasado',
} as const;
