/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaParcelamentoDtoParcelamentoTipo =
  (typeof RespostaParcelamentoDtoParcelamentoTipo)[keyof typeof RespostaParcelamentoDtoParcelamentoTipo];

export const RespostaParcelamentoDtoParcelamentoTipo = {
  compra_cartao: 'compra_cartao',
  divida: 'divida',
} as const;
