/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaPagamentoFaturaDtoTransacaoStatus =
  (typeof RespostaPagamentoFaturaDtoTransacaoStatus)[keyof typeof RespostaPagamentoFaturaDtoTransacaoStatus];

export const RespostaPagamentoFaturaDtoTransacaoStatus = {
  pago: 'pago',
  pendente: 'pendente',
} as const;
