/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaRecorrenciaDtoRecorrenciaFormaPagamento } from './respostaRecorrenciaDtoRecorrenciaFormaPagamento';
import type { RespostaRecorrenciaDtoRecorrenciaFrequencia } from './respostaRecorrenciaDtoRecorrenciaFrequencia';
import type { RespostaRecorrenciaDtoRecorrenciaTipo } from './respostaRecorrenciaDtoRecorrenciaTipo';

export type RespostaRecorrenciaDtoRecorrencia = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  tipo: RespostaRecorrenciaDtoRecorrenciaTipo;
  descricao: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorCentavos: number;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  formaPagamento: RespostaRecorrenciaDtoRecorrenciaFormaPagamento;
  contaId: string | null;
  frequencia: RespostaRecorrenciaDtoRecorrenciaFrequencia;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  dia: number;
  dataInicio: string;
  /** @nullable */
  dataFim: string | null;
  /** @nullable */
  proximaGeracao: string | null;
  ativa: boolean;
};
