/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaPagamentoFaturaDtoImpactoCartao } from './respostaPagamentoFaturaDtoImpactoCartao';
import type { RespostaPagamentoFaturaDtoImpactoOrcamento } from './respostaPagamentoFaturaDtoImpactoOrcamento';

export type RespostaPagamentoFaturaDtoImpacto = {
  orcamento?: RespostaPagamentoFaturaDtoImpactoOrcamento;
  cartao?: RespostaPagamentoFaturaDtoImpactoCartao;
};
