/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaPagamentoFaturaDtoTransacaoTipo =
  (typeof RespostaPagamentoFaturaDtoTransacaoTipo)[keyof typeof RespostaPagamentoFaturaDtoTransacaoTipo];

export const RespostaPagamentoFaturaDtoTransacaoTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
