/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaParcelaDtoParcelamentoTipo =
  (typeof RespostaParcelaDtoParcelamentoTipo)[keyof typeof RespostaParcelaDtoParcelamentoTipo];

export const RespostaParcelaDtoParcelamentoTipo = {
  compra_cartao: 'compra_cartao',
  divida: 'divida',
} as const;
