/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaTransacaoDtoImpactoCartao } from './respostaTransacaoDtoImpactoCartao';
import type { RespostaTransacaoDtoImpactoOrcamento } from './respostaTransacaoDtoImpactoOrcamento';

export type RespostaTransacaoDtoImpacto = {
  orcamento?: RespostaTransacaoDtoImpactoOrcamento;
  cartao?: RespostaTransacaoDtoImpactoCartao;
};
