/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaPagamentoFaturaDtoFatura } from './respostaPagamentoFaturaDtoFatura';
import type { RespostaPagamentoFaturaDtoImpacto } from './respostaPagamentoFaturaDtoImpacto';
import type { RespostaPagamentoFaturaDtoTransacao } from './respostaPagamentoFaturaDtoTransacao';

export interface RespostaPagamentoFaturaDto {
  fatura: RespostaPagamentoFaturaDtoFatura;
  transacao: RespostaPagamentoFaturaDtoTransacao;
  impacto: RespostaPagamentoFaturaDtoImpacto;
}
