/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaRecorrenciaDtoOcorrenciasItemAnexosItem } from './respostaRecorrenciaDtoOcorrenciasItemAnexosItem';
import type { RespostaRecorrenciaDtoOcorrenciasItemFormaPagamento } from './respostaRecorrenciaDtoOcorrenciasItemFormaPagamento';
import type { RespostaRecorrenciaDtoOcorrenciasItemNatureza } from './respostaRecorrenciaDtoOcorrenciasItemNatureza';
import type { RespostaRecorrenciaDtoOcorrenciasItemOrigem } from './respostaRecorrenciaDtoOcorrenciasItemOrigem';
import type { RespostaRecorrenciaDtoOcorrenciasItemStatus } from './respostaRecorrenciaDtoOcorrenciasItemStatus';
import type { RespostaRecorrenciaDtoOcorrenciasItemTipo } from './respostaRecorrenciaDtoOcorrenciasItemTipo';

export type RespostaRecorrenciaDtoOcorrenciasItem = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  tipo: RespostaRecorrenciaDtoOcorrenciasItemTipo;
  descricao: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorCentavos: number;
  data: string;
  status: RespostaRecorrenciaDtoOcorrenciasItemStatus;
  formaPagamento: RespostaRecorrenciaDtoOcorrenciasItemFormaPagamento;
  origem: RespostaRecorrenciaDtoOcorrenciasItemOrigem;
  natureza: RespostaRecorrenciaDtoOcorrenciasItemNatureza;
  /** @nullable */
  observacao: string | null;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  contaId: string | null;
  cartaoId: string | null;
  faturaId: string | null;
  recorrenciaId: string | null;
  parcelamentoId: string | null;
  anexos: RespostaRecorrenciaDtoOcorrenciasItemAnexosItem[];
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  criadoEm: string;
  /** @pattern ^(?:(?:\d\d[2468][048]|\d\d[13579][26]|\d\d0[48]|[02468][048]00|[13579][26]00)-02-29|\d{4}-(?:(?:0[13578]|1[02])-(?:0[1-9]|[12]\d|3[01])|(?:0[469]|11)-(?:0[1-9]|[12]\d|30)|(?:02)-(?:0[1-9]|1\d|2[0-8])))T(?:(?:[01]\d|2[0-3]):[0-5]\d:[0-5]\d(?:\.\d+)?(?:Z))$ */
  atualizadoEm: string;
};
