/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaRecorrenciaDtoOcorrenciasItem } from './respostaRecorrenciaDtoOcorrenciasItem';
import type { RespostaRecorrenciaDtoRecorrencia } from './respostaRecorrenciaDtoRecorrencia';

export interface RespostaRecorrenciaDto {
  recorrencia: RespostaRecorrenciaDtoRecorrencia;
  ocorrencias: RespostaRecorrenciaDtoOcorrenciasItem[];
}
