/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaTransacaoDtoTransacaoAnexosItemTipo =
  (typeof RespostaTransacaoDtoTransacaoAnexosItemTipo)[keyof typeof RespostaTransacaoDtoTransacaoAnexosItemTipo];

export const RespostaTransacaoDtoTransacaoAnexosItemTipo = {
  foto: 'foto',
  pdf: 'pdf',
  comprovante: 'comprovante',
} as const;
