/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaRecorrenciaDtoRecorrenciaTipo =
  (typeof RespostaRecorrenciaDtoRecorrenciaTipo)[keyof typeof RespostaRecorrenciaDtoRecorrenciaTipo];

export const RespostaRecorrenciaDtoRecorrenciaTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
