/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaTransacaoDtoImpacto } from './respostaTransacaoDtoImpacto';
import type { RespostaTransacaoDtoTransacao } from './respostaTransacaoDtoTransacao';

export interface RespostaTransacaoDto {
  transacao: RespostaTransacaoDtoTransacao;
  impacto: RespostaTransacaoDtoImpacto;
}
