/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaTransacaoDtoTransacaoTipo =
  (typeof RespostaTransacaoDtoTransacaoTipo)[keyof typeof RespostaTransacaoDtoTransacaoTipo];

export const RespostaTransacaoDtoTransacaoTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
