/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaParcelaDtoParcela } from './respostaParcelaDtoParcela';
import type { RespostaParcelaDtoParcelamento } from './respostaParcelaDtoParcelamento';

export interface RespostaParcelaDto {
  parcela: RespostaParcelaDtoParcela;
  parcelamento: RespostaParcelaDtoParcelamento;
}
