/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaParcelamentoDtoImpactoCartao } from './respostaParcelamentoDtoImpactoCartao';
import type { RespostaParcelamentoDtoImpactoOrcamento } from './respostaParcelamentoDtoImpactoOrcamento';

export type RespostaParcelamentoDtoImpacto = {
  orcamento?: RespostaParcelamentoDtoImpactoOrcamento;
  cartao?: RespostaParcelamentoDtoImpactoCartao;
};
