/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type RespostaRecorrenciaDtoOcorrenciasItemStatus =
  (typeof RespostaRecorrenciaDtoOcorrenciasItemStatus)[keyof typeof RespostaRecorrenciaDtoOcorrenciasItemStatus];

export const RespostaRecorrenciaDtoOcorrenciasItemStatus = {
  pago: 'pago',
  pendente: 'pendente',
} as const;
