/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { RespostaParcelaDtoParcelamentoProgresso } from './respostaParcelaDtoParcelamentoProgresso';
import type { RespostaParcelaDtoParcelamentoProximaParcela } from './respostaParcelaDtoParcelamentoProximaParcela';
import type { RespostaParcelaDtoParcelamentoStatus } from './respostaParcelaDtoParcelamentoStatus';
import type { RespostaParcelaDtoParcelamentoTipo } from './respostaParcelaDtoParcelamentoTipo';

export type RespostaParcelaDtoParcelamento = {
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  id: string;
  nome: string;
  tipo: RespostaParcelaDtoParcelamentoTipo;
  status: RespostaParcelaDtoParcelamentoStatus;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorTotalCentavos: number;
  valorFinanciadoCentavos: number | null;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  totalParcelas: number;
  /** @nullable */
  taxaJurosMensal: number | null;
  dataInicio: string;
  /** @nullable */
  observacao: string | null;
  /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
  categoriaId: string;
  cartaoId: string | null;
  progresso: RespostaParcelaDtoParcelamentoProgresso;
  proximaParcela: RespostaParcelaDtoParcelamentoProximaParcela;
};
