/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type ResultadoSimulacaoDtoParcelasItem = {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  numero: number;
  vencimento: string;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  jurosCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  amortizacaoCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  saldoDevedorCentavos: number;
};
