/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { ResultadoSimulacaoDtoParcelasItem } from './resultadoSimulacaoDtoParcelasItem';

export interface ResultadoSimulacaoDto {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorFinanciadoCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  valorTotalCentavos: number;
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  jurosTotalCentavos: number;
  parcelas: ResultadoSimulacaoDtoParcelasItem[];
}
