/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export interface ResultadoLoteDto {
  /**
   * @minimum -9007199254740991
   * @maximum 9007199254740991
   */
  afetadas: number;
}
