/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export const SaudeDtoValue = {
  status: 'ok',
} as const;
export type SaudeDto = typeof SaudeDtoValue;
