/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type SaudeDtoStatus = (typeof SaudeDtoStatus)[keyof typeof SaudeDtoStatus];

export const SaudeDtoStatus = {
  ok: 'ok',
} as const;
