/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type SessaoDtoAceitesPendentesItem =
  (typeof SessaoDtoAceitesPendentesItem)[keyof typeof SessaoDtoAceitesPendentesItem];

export const SessaoDtoAceitesPendentesItem = {
  termos: 'termos',
  privacidade: 'privacidade',
} as const;
