/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { SessaoDtoAceitesPendentesItem } from './sessaoDtoAceitesPendentesItem';
import type { SessaoDtoTokens } from './sessaoDtoTokens';
import type { SessaoDtoUsuario } from './sessaoDtoUsuario';

export interface SessaoDto {
  usuario: SessaoDtoUsuario;
  tokens: SessaoDtoTokens;
  aceitesPendentes: SessaoDtoAceitesPendentesItem[];
}
