/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type TotaisTransacoesStatus =
  (typeof TotaisTransacoesStatus)[keyof typeof TotaisTransacoesStatus];

export const TotaisTransacoesStatus = {
  pago: 'pago',
  pendente: 'pendente',
} as const;
