/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type TotaisTransacoesTipo = (typeof TotaisTransacoesTipo)[keyof typeof TotaisTransacoesTipo];

export const TotaisTransacoesTipo = {
  receita: 'receita',
  despesa: 'despesa',
} as const;
