/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type TotaisTransacoesFormaPagamento =
  (typeof TotaisTransacoesFormaPagamento)[keyof typeof TotaisTransacoesFormaPagamento];

export const TotaisTransacoesFormaPagamento = {
  cartao_credito: 'cartao_credito',
  pix: 'pix',
  debito: 'debito',
  dinheiro: 'dinheiro',
  boleto: 'boleto',
} as const;
