/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { TotaisTransacoesFormaPagamento } from './totaisTransacoesFormaPagamento';
import type { TotaisTransacoesOrigem } from './totaisTransacoesOrigem';
import type { TotaisTransacoesStatus } from './totaisTransacoesStatus';
import type { TotaisTransacoesTipo } from './totaisTransacoesTipo';

export type TotaisTransacoesParams = {
  de?: string;
  ate?: string;
  tipo?: TotaisTransacoesTipo;
  /**
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  categoriaId?: string;
  formaPagamento?: TotaisTransacoesFormaPagamento;
  /**
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  cartaoId?: string;
  /**
   * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
   */
  contaId?: string;
  status?: TotaisTransacoesStatus;
  origem?: TotaisTransacoesOrigem;
  /**
   * @minLength 1
   * @maxLength 100
   */
  texto?: string;
};
