/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type TransacaoDtoNatureza = (typeof TransacaoDtoNatureza)[keyof typeof TransacaoDtoNatureza];

export const TransacaoDtoNatureza = {
  normal: 'normal',
  pagamento_fatura: 'pagamento_fatura',
  transferencia: 'transferencia',
} as const;
