/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type TransacaoDtoStatus = (typeof TransacaoDtoStatus)[keyof typeof TransacaoDtoStatus];

export const TransacaoDtoStatus = {
  pago: 'pago',
  pendente: 'pendente',
} as const;
