/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type TransacaoDtoOrigem = (typeof TransacaoDtoOrigem)[keyof typeof TransacaoDtoOrigem];

export const TransacaoDtoOrigem = {
  manual: 'manual',
  mony: 'mony',
  open_finance: 'open_finance',
  foto: 'foto',
} as const;
