/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */

export type TransacaoDtoAnexosItemTipo =
  (typeof TransacaoDtoAnexosItemTipo)[keyof typeof TransacaoDtoAnexosItemTipo];

export const TransacaoDtoAnexosItemTipo = {
  foto: 'foto',
  pdf: 'pdf',
  comprovante: 'comprovante',
} as const;
