/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import type { VinculoSocialDtoProvedor } from './vinculoSocialDtoProvedor';

export interface VinculoSocialDto {
  provedor: VinculoSocialDtoProvedor;
  /**
   * @minLength 20
   * @maxLength 8000
   */
  idToken: string;
  /**
   * @minLength 16
   * @maxLength 200
   */
  nonce?: string;
}
