/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AtualizacaoParcelamentoDto,
  DetalheParcelamentoDto,
  ListaParcelamentosDto,
  ListarParcelamentosParams,
  NovoParcelamentoDto,
  PagamentoParcelaDto,
  RespostaParcelaDto,
  RespostaParcelamentoDto,
  ResultadoSimulacaoDto,
  SimulacaoParcelamentoDto,
} from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListarParcelamentosUrl = (params?: ListarParcelamentosParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/parcelamentos?${stringifiedParams}`
    : `/v1/parcelamentos`;
};

export const listarParcelamentos = async (
  params?: ListarParcelamentosParams,
  options?: Parameters<typeof requisicao>[1],
): Promise<ListaParcelamentosDto> => {
  return requisicao<ListaParcelamentosDto>(getListarParcelamentosUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getListarParcelamentosQueryKey = (params?: ListarParcelamentosParams) => {
  return [`/v1/parcelamentos`, ...(params ? [params] : [])] as const;
};

export const getListarParcelamentosQueryOptions = <
  TData = Awaited<ReturnType<typeof listarParcelamentos>>,
  TError = unknown,
>(
  params?: ListarParcelamentosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listarParcelamentos>>, TError, TData>
    >;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListarParcelamentosQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listarParcelamentos>>> = ({ signal }) =>
    listarParcelamentos(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listarParcelamentos>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListarParcelamentosQueryResult = NonNullable<
  Awaited<ReturnType<typeof listarParcelamentos>>
>;
export type ListarParcelamentosQueryError = unknown;

export function useListarParcelamentos<
  TData = Awaited<ReturnType<typeof listarParcelamentos>>,
  TError = unknown,
>(
  params: undefined | ListarParcelamentosParams,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listarParcelamentos>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarParcelamentos>>,
          TError,
          Awaited<ReturnType<typeof listarParcelamentos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarParcelamentos<
  TData = Awaited<ReturnType<typeof listarParcelamentos>>,
  TError = unknown,
>(
  params?: ListarParcelamentosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listarParcelamentos>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarParcelamentos>>,
          TError,
          Awaited<ReturnType<typeof listarParcelamentos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarParcelamentos<
  TData = Awaited<ReturnType<typeof listarParcelamentos>>,
  TError = unknown,
>(
  params?: ListarParcelamentosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listarParcelamentos>>, TError, TData>
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListarParcelamentos<
  TData = Awaited<ReturnType<typeof listarParcelamentos>>,
  TError = unknown,
>(
  params?: ListarParcelamentosParams,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listarParcelamentos>>, TError, TData>
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListarParcelamentosQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getRegistrarParcelamentosUrl = () => {
  return `/v1/parcelamentos`;
};

export const registrarParcelamentos = async (
  novoParcelamentoDto: NovoParcelamentoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<RespostaParcelamentoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<RespostaParcelamentoDto>(getRegistrarParcelamentosUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(novoParcelamentoDto),
  });
};

export const getRegistrarParcelamentosMutationKey = () => ['registrarParcelamentos'] as const;

export const getRegistrarParcelamentosMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registrarParcelamentos>>,
    TError,
    RegistrarParcelamentosMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registrarParcelamentos>>,
  TError,
  RegistrarParcelamentosMutationVariables,
  TContext
> => {
  const mutationKey = getRegistrarParcelamentosMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registrarParcelamentos>>,
    RegistrarParcelamentosMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return registrarParcelamentos(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegistrarParcelamentosMutationResult = NonNullable<
  Awaited<ReturnType<typeof registrarParcelamentos>>
>;
export type RegistrarParcelamentosMutationBody = NovoParcelamentoDto;
export type RegistrarParcelamentosMutationError = unknown;
export type RegistrarParcelamentosMutationVariables = { data: NovoParcelamentoDto };

export const useRegistrarParcelamentos = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registrarParcelamentos>>,
      TError,
      RegistrarParcelamentosMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof registrarParcelamentos>>,
  TError,
  RegistrarParcelamentosMutationVariables,
  TContext
> => {
  return useMutation(getRegistrarParcelamentosMutationOptions(options), queryClient);
};
export const getSimularParcelamentosUrl = () => {
  return `/v1/parcelamentos/simular`;
};

export const simularParcelamentos = async (
  simulacaoParcelamentoDto: SimulacaoParcelamentoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<ResultadoSimulacaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<ResultadoSimulacaoDto>(getSimularParcelamentosUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(simulacaoParcelamentoDto),
  });
};

export const getSimularParcelamentosMutationKey = () => ['simularParcelamentos'] as const;

export const getSimularParcelamentosMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof simularParcelamentos>>,
    TError,
    SimularParcelamentosMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof simularParcelamentos>>,
  TError,
  SimularParcelamentosMutationVariables,
  TContext
> => {
  const mutationKey = getSimularParcelamentosMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof simularParcelamentos>>,
    SimularParcelamentosMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return simularParcelamentos(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type SimularParcelamentosMutationResult = NonNullable<
  Awaited<ReturnType<typeof simularParcelamentos>>
>;
export type SimularParcelamentosMutationBody = SimulacaoParcelamentoDto;
export type SimularParcelamentosMutationError = unknown;
export type SimularParcelamentosMutationVariables = { data: SimulacaoParcelamentoDto };

export const useSimularParcelamentos = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof simularParcelamentos>>,
      TError,
      SimularParcelamentosMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof simularParcelamentos>>,
  TError,
  SimularParcelamentosMutationVariables,
  TContext
> => {
  return useMutation(getSimularParcelamentosMutationOptions(options), queryClient);
};
export const getBuscarParcelamentosUrl = (id: string) => {
  return `/v1/parcelamentos/${id}`;
};

export const buscarParcelamentos = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<DetalheParcelamentoDto> => {
  return requisicao<DetalheParcelamentoDto>(getBuscarParcelamentosUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getBuscarParcelamentosQueryKey = (id: string) => {
  return [`/v1/parcelamentos/${id}`] as const;
};

export const getBuscarParcelamentosQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarParcelamentos>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof buscarParcelamentos>>, TError, TData>
    >;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBuscarParcelamentosQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof buscarParcelamentos>>> = ({ signal }) =>
    buscarParcelamentos(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof buscarParcelamentos>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type BuscarParcelamentosQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarParcelamentos>>
>;
export type BuscarParcelamentosQueryError = unknown;

export function useBuscarParcelamentos<
  TData = Awaited<ReturnType<typeof buscarParcelamentos>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof buscarParcelamentos>>, TError, TData>
    > &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarParcelamentos>>,
          TError,
          Awaited<ReturnType<typeof buscarParcelamentos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarParcelamentos<
  TData = Awaited<ReturnType<typeof buscarParcelamentos>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof buscarParcelamentos>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarParcelamentos>>,
          TError,
          Awaited<ReturnType<typeof buscarParcelamentos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarParcelamentos<
  TData = Awaited<ReturnType<typeof buscarParcelamentos>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof buscarParcelamentos>>, TError, TData>
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBuscarParcelamentos<
  TData = Awaited<ReturnType<typeof buscarParcelamentos>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof buscarParcelamentos>>, TError, TData>
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBuscarParcelamentosQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getAtualizarParcelamentosUrl = (id: string) => {
  return `/v1/parcelamentos/${id}`;
};

export const atualizarParcelamentos = async (
  id: string,
  atualizacaoParcelamentoDto: AtualizacaoParcelamentoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<DetalheParcelamentoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<DetalheParcelamentoDto>(getAtualizarParcelamentosUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizacaoParcelamentoDto),
  });
};

export const getAtualizarParcelamentosMutationKey = () => ['atualizarParcelamentos'] as const;

export const getAtualizarParcelamentosMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarParcelamentos>>,
    TError,
    AtualizarParcelamentosMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarParcelamentos>>,
  TError,
  AtualizarParcelamentosMutationVariables,
  TContext
> => {
  const mutationKey = getAtualizarParcelamentosMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarParcelamentos>>,
    AtualizarParcelamentosMutationVariables
  > = (props) => {
    const { id, data } = props ?? {};

    return atualizarParcelamentos(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarParcelamentosMutationResult = NonNullable<
  Awaited<ReturnType<typeof atualizarParcelamentos>>
>;
export type AtualizarParcelamentosMutationBody = AtualizacaoParcelamentoDto;
export type AtualizarParcelamentosMutationError = unknown;
export type AtualizarParcelamentosMutationVariables = {
  id: string;
  data: AtualizacaoParcelamentoDto;
};

export const useAtualizarParcelamentos = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarParcelamentos>>,
      TError,
      AtualizarParcelamentosMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarParcelamentos>>,
  TError,
  AtualizarParcelamentosMutationVariables,
  TContext
> => {
  return useMutation(getAtualizarParcelamentosMutationOptions(options), queryClient);
};
export const getCancelarParcelamentosUrl = (id: string) => {
  return `/v1/parcelamentos/${id}`;
};

export const cancelarParcelamentos = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  return requisicao<void>(getCancelarParcelamentosUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getCancelarParcelamentosMutationKey = () => ['cancelarParcelamentos'] as const;

export const getCancelarParcelamentosMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof cancelarParcelamentos>>,
    TError,
    CancelarParcelamentosMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof cancelarParcelamentos>>,
  TError,
  CancelarParcelamentosMutationVariables,
  TContext
> => {
  const mutationKey = getCancelarParcelamentosMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof cancelarParcelamentos>>,
    CancelarParcelamentosMutationVariables
  > = (props) => {
    const { id } = props ?? {};

    return cancelarParcelamentos(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CancelarParcelamentosMutationResult = NonNullable<
  Awaited<ReturnType<typeof cancelarParcelamentos>>
>;

export type CancelarParcelamentosMutationError = unknown;
export type CancelarParcelamentosMutationVariables = { id: string };

export const useCancelarParcelamentos = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof cancelarParcelamentos>>,
      TError,
      CancelarParcelamentosMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof cancelarParcelamentos>>,
  TError,
  CancelarParcelamentosMutationVariables,
  TContext
> => {
  return useMutation(getCancelarParcelamentosMutationOptions(options), queryClient);
};
export const getPagarParcelasUrl = (id: string) => {
  return `/v1/parcelas/${id}/pagar`;
};

export const pagarParcelas = async (
  id: string,
  pagamentoParcelaDto: PagamentoParcelaDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<RespostaParcelaDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<RespostaParcelaDto>(getPagarParcelasUrl(id), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(pagamentoParcelaDto),
  });
};

export const getPagarParcelasMutationKey = () => ['pagarParcelas'] as const;

export const getPagarParcelasMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof pagarParcelas>>,
    TError,
    PagarParcelasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof pagarParcelas>>,
  TError,
  PagarParcelasMutationVariables,
  TContext
> => {
  const mutationKey = getPagarParcelasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof pagarParcelas>>,
    PagarParcelasMutationVariables
  > = (props) => {
    const { id, data } = props ?? {};

    return pagarParcelas(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PagarParcelasMutationResult = NonNullable<Awaited<ReturnType<typeof pagarParcelas>>>;
export type PagarParcelasMutationBody = PagamentoParcelaDto;
export type PagarParcelasMutationError = unknown;
export type PagarParcelasMutationVariables = { id: string; data: PagamentoParcelaDto };

export const usePagarParcelas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof pagarParcelas>>,
      TError,
      PagarParcelasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof pagarParcelas>>,
  TError,
  PagarParcelasMutationVariables,
  TContext
> => {
  return useMutation(getPagarParcelasMutationOptions(options), queryClient);
};
export const getDesfazerParcelasUrl = (id: string) => {
  return `/v1/parcelas/${id}/desfazer`;
};

export const desfazerParcelas = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<RespostaParcelaDto> => {
  return requisicao<RespostaParcelaDto>(getDesfazerParcelasUrl(id), {
    ...options,
    method: 'POST',
  });
};

export const getDesfazerParcelasMutationKey = () => ['desfazerParcelas'] as const;

export const getDesfazerParcelasMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof desfazerParcelas>>,
    TError,
    DesfazerParcelasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof desfazerParcelas>>,
  TError,
  DesfazerParcelasMutationVariables,
  TContext
> => {
  const mutationKey = getDesfazerParcelasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof desfazerParcelas>>,
    DesfazerParcelasMutationVariables
  > = (props) => {
    const { id } = props ?? {};

    return desfazerParcelas(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type DesfazerParcelasMutationResult = NonNullable<
  Awaited<ReturnType<typeof desfazerParcelas>>
>;

export type DesfazerParcelasMutationError = unknown;
export type DesfazerParcelasMutationVariables = { id: string };

export const useDesfazerParcelas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof desfazerParcelas>>,
      TError,
      DesfazerParcelasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof desfazerParcelas>>,
  TError,
  DesfazerParcelasMutationVariables,
  TContext
> => {
  return useMutation(getDesfazerParcelasMutationOptions(options), queryClient);
};
