/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { EnvioArquivoDto, LeituraArquivoDto, NovoArquivoDto } from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPrepararArquivosUrl = () => {
  return `/v1/arquivos`;
};

export const prepararArquivos = async (
  novoArquivoDto: NovoArquivoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<EnvioArquivoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<EnvioArquivoDto>(getPrepararArquivosUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(novoArquivoDto),
  });
};

export const getPrepararArquivosMutationKey = () => ['prepararArquivos'] as const;

export const getPrepararArquivosMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof prepararArquivos>>,
    TError,
    PrepararArquivosMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof prepararArquivos>>,
  TError,
  PrepararArquivosMutationVariables,
  TContext
> => {
  const mutationKey = getPrepararArquivosMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof prepararArquivos>>,
    PrepararArquivosMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return prepararArquivos(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type PrepararArquivosMutationResult = NonNullable<
  Awaited<ReturnType<typeof prepararArquivos>>
>;
export type PrepararArquivosMutationBody = NovoArquivoDto;
export type PrepararArquivosMutationError = unknown;
export type PrepararArquivosMutationVariables = { data: NovoArquivoDto };

export const usePrepararArquivos = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof prepararArquivos>>,
      TError,
      PrepararArquivosMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof prepararArquivos>>,
  TError,
  PrepararArquivosMutationVariables,
  TContext
> => {
  return useMutation(getPrepararArquivosMutationOptions(options), queryClient);
};
export const getLerArquivosUrl = (id: string) => {
  return `/v1/arquivos/${id}`;
};

export const lerArquivos = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<LeituraArquivoDto> => {
  return requisicao<LeituraArquivoDto>(getLerArquivosUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getLerArquivosQueryKey = (id: string) => {
  return [`/v1/arquivos/${id}`] as const;
};

export const getLerArquivosQueryOptions = <
  TData = Awaited<ReturnType<typeof lerArquivos>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof lerArquivos>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getLerArquivosQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof lerArquivos>>> = ({ signal }) =>
    lerArquivos(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof lerArquivos>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type LerArquivosQueryResult = NonNullable<Awaited<ReturnType<typeof lerArquivos>>>;
export type LerArquivosQueryError = unknown;

export function useLerArquivos<TData = Awaited<ReturnType<typeof lerArquivos>>, TError = unknown>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof lerArquivos>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof lerArquivos>>,
          TError,
          Awaited<ReturnType<typeof lerArquivos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useLerArquivos<TData = Awaited<ReturnType<typeof lerArquivos>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof lerArquivos>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof lerArquivos>>,
          TError,
          Awaited<ReturnType<typeof lerArquivos>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useLerArquivos<TData = Awaited<ReturnType<typeof lerArquivos>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof lerArquivos>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useLerArquivos<TData = Awaited<ReturnType<typeof lerArquivos>>, TError = unknown>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof lerArquivos>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getLerArquivosQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}
