/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AtualizacaoOnboardingDto,
  AtualizacaoPerfilDto,
  OnboardingDto,
  PerfilDto,
  RegistroDispositivoDto,
} from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getPerfilUsuariosUrl = () => {
  return `/v1/me`;
};

export const perfilUsuarios = async (
  options?: Parameters<typeof requisicao>[1],
): Promise<PerfilDto> => {
  return requisicao<PerfilDto>(getPerfilUsuariosUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getPerfilUsuariosQueryKey = () => {
  return [`/v1/me`] as const;
};

export const getPerfilUsuariosQueryOptions = <
  TData = Awaited<ReturnType<typeof perfilUsuarios>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof perfilUsuarios>>, TError, TData>>;
  request?: SecondParameter<typeof requisicao>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getPerfilUsuariosQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof perfilUsuarios>>> = ({ signal }) =>
    perfilUsuarios({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof perfilUsuarios>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type PerfilUsuariosQueryResult = NonNullable<Awaited<ReturnType<typeof perfilUsuarios>>>;
export type PerfilUsuariosQueryError = unknown;

export function usePerfilUsuarios<
  TData = Awaited<ReturnType<typeof perfilUsuarios>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof perfilUsuarios>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof perfilUsuarios>>,
          TError,
          Awaited<ReturnType<typeof perfilUsuarios>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePerfilUsuarios<
  TData = Awaited<ReturnType<typeof perfilUsuarios>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof perfilUsuarios>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof perfilUsuarios>>,
          TError,
          Awaited<ReturnType<typeof perfilUsuarios>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function usePerfilUsuarios<
  TData = Awaited<ReturnType<typeof perfilUsuarios>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof perfilUsuarios>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function usePerfilUsuarios<
  TData = Awaited<ReturnType<typeof perfilUsuarios>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof perfilUsuarios>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getPerfilUsuariosQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getAtualizarPerfilUsuariosUrl = () => {
  return `/v1/me`;
};

export const atualizarPerfilUsuarios = async (
  atualizacaoPerfilDto: AtualizacaoPerfilDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<PerfilDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<PerfilDto>(getAtualizarPerfilUsuariosUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizacaoPerfilDto),
  });
};

export const getAtualizarPerfilUsuariosMutationKey = () => ['atualizarPerfilUsuarios'] as const;

export const getAtualizarPerfilUsuariosMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarPerfilUsuarios>>,
    TError,
    AtualizarPerfilUsuariosMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarPerfilUsuarios>>,
  TError,
  AtualizarPerfilUsuariosMutationVariables,
  TContext
> => {
  const mutationKey = getAtualizarPerfilUsuariosMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarPerfilUsuarios>>,
    AtualizarPerfilUsuariosMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return atualizarPerfilUsuarios(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarPerfilUsuariosMutationResult = NonNullable<
  Awaited<ReturnType<typeof atualizarPerfilUsuarios>>
>;
export type AtualizarPerfilUsuariosMutationBody = AtualizacaoPerfilDto;
export type AtualizarPerfilUsuariosMutationError = unknown;
export type AtualizarPerfilUsuariosMutationVariables = { data: AtualizacaoPerfilDto };

export const useAtualizarPerfilUsuarios = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarPerfilUsuarios>>,
      TError,
      AtualizarPerfilUsuariosMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarPerfilUsuarios>>,
  TError,
  AtualizarPerfilUsuariosMutationVariables,
  TContext
> => {
  return useMutation(getAtualizarPerfilUsuariosMutationOptions(options), queryClient);
};
export const getRegistrarDispositivoUsuariosUrl = () => {
  return `/v1/me/dispositivos`;
};

export const registrarDispositivoUsuarios = async (
  registroDispositivoDto: RegistroDispositivoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<void>(getRegistrarDispositivoUsuariosUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(registroDispositivoDto),
  });
};

export const getRegistrarDispositivoUsuariosMutationKey = () =>
  ['registrarDispositivoUsuarios'] as const;

export const getRegistrarDispositivoUsuariosMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registrarDispositivoUsuarios>>,
    TError,
    RegistrarDispositivoUsuariosMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registrarDispositivoUsuarios>>,
  TError,
  RegistrarDispositivoUsuariosMutationVariables,
  TContext
> => {
  const mutationKey = getRegistrarDispositivoUsuariosMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registrarDispositivoUsuarios>>,
    RegistrarDispositivoUsuariosMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return registrarDispositivoUsuarios(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegistrarDispositivoUsuariosMutationResult = NonNullable<
  Awaited<ReturnType<typeof registrarDispositivoUsuarios>>
>;
export type RegistrarDispositivoUsuariosMutationBody = RegistroDispositivoDto;
export type RegistrarDispositivoUsuariosMutationError = unknown;
export type RegistrarDispositivoUsuariosMutationVariables = { data: RegistroDispositivoDto };

export const useRegistrarDispositivoUsuarios = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registrarDispositivoUsuarios>>,
      TError,
      RegistrarDispositivoUsuariosMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof registrarDispositivoUsuarios>>,
  TError,
  RegistrarDispositivoUsuariosMutationVariables,
  TContext
> => {
  return useMutation(getRegistrarDispositivoUsuariosMutationOptions(options), queryClient);
};
export const getOnboardingUsuariosUrl = () => {
  return `/v1/me/onboarding`;
};

export const onboardingUsuarios = async (
  options?: Parameters<typeof requisicao>[1],
): Promise<OnboardingDto> => {
  return requisicao<OnboardingDto>(getOnboardingUsuariosUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getOnboardingUsuariosQueryKey = () => {
  return [`/v1/me/onboarding`] as const;
};

export const getOnboardingUsuariosQueryOptions = <
  TData = Awaited<ReturnType<typeof onboardingUsuarios>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingUsuarios>>, TError, TData>>;
  request?: SecondParameter<typeof requisicao>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getOnboardingUsuariosQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof onboardingUsuarios>>> = ({ signal }) =>
    onboardingUsuarios({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof onboardingUsuarios>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type OnboardingUsuariosQueryResult = NonNullable<
  Awaited<ReturnType<typeof onboardingUsuarios>>
>;
export type OnboardingUsuariosQueryError = unknown;

export function useOnboardingUsuarios<
  TData = Awaited<ReturnType<typeof onboardingUsuarios>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingUsuarios>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof onboardingUsuarios>>,
          TError,
          Awaited<ReturnType<typeof onboardingUsuarios>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnboardingUsuarios<
  TData = Awaited<ReturnType<typeof onboardingUsuarios>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof onboardingUsuarios>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof onboardingUsuarios>>,
          TError,
          Awaited<ReturnType<typeof onboardingUsuarios>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useOnboardingUsuarios<
  TData = Awaited<ReturnType<typeof onboardingUsuarios>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingUsuarios>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useOnboardingUsuarios<
  TData = Awaited<ReturnType<typeof onboardingUsuarios>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof onboardingUsuarios>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getOnboardingUsuariosQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getAtualizarOnboardingUsuariosUrl = () => {
  return `/v1/me/onboarding`;
};

export const atualizarOnboardingUsuarios = async (
  atualizacaoOnboardingDto: AtualizacaoOnboardingDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<OnboardingDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<OnboardingDto>(getAtualizarOnboardingUsuariosUrl(), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizacaoOnboardingDto),
  });
};

export const getAtualizarOnboardingUsuariosMutationKey = () =>
  ['atualizarOnboardingUsuarios'] as const;

export const getAtualizarOnboardingUsuariosMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarOnboardingUsuarios>>,
    TError,
    AtualizarOnboardingUsuariosMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarOnboardingUsuarios>>,
  TError,
  AtualizarOnboardingUsuariosMutationVariables,
  TContext
> => {
  const mutationKey = getAtualizarOnboardingUsuariosMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarOnboardingUsuarios>>,
    AtualizarOnboardingUsuariosMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return atualizarOnboardingUsuarios(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarOnboardingUsuariosMutationResult = NonNullable<
  Awaited<ReturnType<typeof atualizarOnboardingUsuarios>>
>;
export type AtualizarOnboardingUsuariosMutationBody = AtualizacaoOnboardingDto;
export type AtualizarOnboardingUsuariosMutationError = unknown;
export type AtualizarOnboardingUsuariosMutationVariables = { data: AtualizacaoOnboardingDto };

export const useAtualizarOnboardingUsuarios = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarOnboardingUsuarios>>,
      TError,
      AtualizarOnboardingUsuariosMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarOnboardingUsuarios>>,
  TError,
  AtualizarOnboardingUsuariosMutationVariables,
  TContext
> => {
  return useMutation(getAtualizarOnboardingUsuariosMutationOptions(options), queryClient);
};
