/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AtualizacaoRecorrenciaDto,
  ListaRecorrenciasDto,
  NovaRecorrenciaDto,
  RecorrenciaDto,
  RespostaRecorrenciaDto,
} from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListarRecorrenciasUrl = () => {
  return `/v1/recorrencias`;
};

export const listarRecorrencias = async (
  options?: Parameters<typeof requisicao>[1],
): Promise<ListaRecorrenciasDto> => {
  return requisicao<ListaRecorrenciasDto>(getListarRecorrenciasUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getListarRecorrenciasQueryKey = () => {
  return [`/v1/recorrencias`] as const;
};

export const getListarRecorrenciasQueryOptions = <
  TData = Awaited<ReturnType<typeof listarRecorrencias>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarRecorrencias>>, TError, TData>>;
  request?: SecondParameter<typeof requisicao>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListarRecorrenciasQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listarRecorrencias>>> = ({ signal }) =>
    listarRecorrencias({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listarRecorrencias>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListarRecorrenciasQueryResult = NonNullable<
  Awaited<ReturnType<typeof listarRecorrencias>>
>;
export type ListarRecorrenciasQueryError = unknown;

export function useListarRecorrencias<
  TData = Awaited<ReturnType<typeof listarRecorrencias>>,
  TError = unknown,
>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarRecorrencias>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarRecorrencias>>,
          TError,
          Awaited<ReturnType<typeof listarRecorrencias>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarRecorrencias<
  TData = Awaited<ReturnType<typeof listarRecorrencias>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof listarRecorrencias>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarRecorrencias>>,
          TError,
          Awaited<ReturnType<typeof listarRecorrencias>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarRecorrencias<
  TData = Awaited<ReturnType<typeof listarRecorrencias>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarRecorrencias>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListarRecorrencias<
  TData = Awaited<ReturnType<typeof listarRecorrencias>>,
  TError = unknown,
>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarRecorrencias>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListarRecorrenciasQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getCriarRecorrenciasUrl = () => {
  return `/v1/recorrencias`;
};

export const criarRecorrencias = async (
  novaRecorrenciaDto: NovaRecorrenciaDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<RespostaRecorrenciaDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<RespostaRecorrenciaDto>(getCriarRecorrenciasUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(novaRecorrenciaDto),
  });
};

export const getCriarRecorrenciasMutationKey = () => ['criarRecorrencias'] as const;

export const getCriarRecorrenciasMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarRecorrencias>>,
    TError,
    CriarRecorrenciasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarRecorrencias>>,
  TError,
  CriarRecorrenciasMutationVariables,
  TContext
> => {
  const mutationKey = getCriarRecorrenciasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarRecorrencias>>,
    CriarRecorrenciasMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return criarRecorrencias(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarRecorrenciasMutationResult = NonNullable<
  Awaited<ReturnType<typeof criarRecorrencias>>
>;
export type CriarRecorrenciasMutationBody = NovaRecorrenciaDto;
export type CriarRecorrenciasMutationError = unknown;
export type CriarRecorrenciasMutationVariables = { data: NovaRecorrenciaDto };

export const useCriarRecorrencias = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarRecorrencias>>,
      TError,
      CriarRecorrenciasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarRecorrencias>>,
  TError,
  CriarRecorrenciasMutationVariables,
  TContext
> => {
  return useMutation(getCriarRecorrenciasMutationOptions(options), queryClient);
};
export const getBuscarRecorrenciasUrl = (id: string) => {
  return `/v1/recorrencias/${id}`;
};

export const buscarRecorrencias = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<RecorrenciaDto> => {
  return requisicao<RecorrenciaDto>(getBuscarRecorrenciasUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getBuscarRecorrenciasQueryKey = (id: string) => {
  return [`/v1/recorrencias/${id}`] as const;
};

export const getBuscarRecorrenciasQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarRecorrencias>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarRecorrencias>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBuscarRecorrenciasQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof buscarRecorrencias>>> = ({ signal }) =>
    buscarRecorrencias(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof buscarRecorrencias>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type BuscarRecorrenciasQueryResult = NonNullable<
  Awaited<ReturnType<typeof buscarRecorrencias>>
>;
export type BuscarRecorrenciasQueryError = unknown;

export function useBuscarRecorrencias<
  TData = Awaited<ReturnType<typeof buscarRecorrencias>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarRecorrencias>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarRecorrencias>>,
          TError,
          Awaited<ReturnType<typeof buscarRecorrencias>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarRecorrencias<
  TData = Awaited<ReturnType<typeof buscarRecorrencias>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<
      UseQueryOptions<Awaited<ReturnType<typeof buscarRecorrencias>>, TError, TData>
    > &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarRecorrencias>>,
          TError,
          Awaited<ReturnType<typeof buscarRecorrencias>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarRecorrencias<
  TData = Awaited<ReturnType<typeof buscarRecorrencias>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarRecorrencias>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBuscarRecorrencias<
  TData = Awaited<ReturnType<typeof buscarRecorrencias>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarRecorrencias>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBuscarRecorrenciasQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getAtualizarRecorrenciasUrl = (id: string) => {
  return `/v1/recorrencias/${id}`;
};

export const atualizarRecorrencias = async (
  id: string,
  atualizacaoRecorrenciaDto: AtualizacaoRecorrenciaDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<RespostaRecorrenciaDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<RespostaRecorrenciaDto>(getAtualizarRecorrenciasUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizacaoRecorrenciaDto),
  });
};

export const getAtualizarRecorrenciasMutationKey = () => ['atualizarRecorrencias'] as const;

export const getAtualizarRecorrenciasMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarRecorrencias>>,
    TError,
    AtualizarRecorrenciasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarRecorrencias>>,
  TError,
  AtualizarRecorrenciasMutationVariables,
  TContext
> => {
  const mutationKey = getAtualizarRecorrenciasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarRecorrencias>>,
    AtualizarRecorrenciasMutationVariables
  > = (props) => {
    const { id, data } = props ?? {};

    return atualizarRecorrencias(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarRecorrenciasMutationResult = NonNullable<
  Awaited<ReturnType<typeof atualizarRecorrencias>>
>;
export type AtualizarRecorrenciasMutationBody = AtualizacaoRecorrenciaDto;
export type AtualizarRecorrenciasMutationError = unknown;
export type AtualizarRecorrenciasMutationVariables = {
  id: string;
  data: AtualizacaoRecorrenciaDto;
};

export const useAtualizarRecorrencias = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarRecorrencias>>,
      TError,
      AtualizarRecorrenciasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarRecorrencias>>,
  TError,
  AtualizarRecorrenciasMutationVariables,
  TContext
> => {
  return useMutation(getAtualizarRecorrenciasMutationOptions(options), queryClient);
};
export const getExcluirRecorrenciasUrl = (id: string) => {
  return `/v1/recorrencias/${id}`;
};

export const excluirRecorrencias = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  return requisicao<void>(getExcluirRecorrenciasUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getExcluirRecorrenciasMutationKey = () => ['excluirRecorrencias'] as const;

export const getExcluirRecorrenciasMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof excluirRecorrencias>>,
    TError,
    ExcluirRecorrenciasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof excluirRecorrencias>>,
  TError,
  ExcluirRecorrenciasMutationVariables,
  TContext
> => {
  const mutationKey = getExcluirRecorrenciasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof excluirRecorrencias>>,
    ExcluirRecorrenciasMutationVariables
  > = (props) => {
    const { id } = props ?? {};

    return excluirRecorrencias(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExcluirRecorrenciasMutationResult = NonNullable<
  Awaited<ReturnType<typeof excluirRecorrencias>>
>;

export type ExcluirRecorrenciasMutationError = unknown;
export type ExcluirRecorrenciasMutationVariables = { id: string };

export const useExcluirRecorrencias = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof excluirRecorrencias>>,
      TError,
      ExcluirRecorrenciasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof excluirRecorrencias>>,
  TError,
  ExcluirRecorrenciasMutationVariables,
  TContext
> => {
  return useMutation(getExcluirRecorrenciasMutationOptions(options), queryClient);
};
