/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type { AtualizacaoContaDto, ContaDto, ListaContasDto, NovaContaDto } from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListarContasUrl = () => {
  return `/v1/contas`;
};

export const listarContas = async (
  options?: Parameters<typeof requisicao>[1],
): Promise<ListaContasDto> => {
  return requisicao<ListaContasDto>(getListarContasUrl(), {
    ...options,
    method: 'GET',
  });
};

export const getListarContasQueryKey = () => {
  return [`/v1/contas`] as const;
};

export const getListarContasQueryOptions = <
  TData = Awaited<ReturnType<typeof listarContas>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarContas>>, TError, TData>>;
  request?: SecondParameter<typeof requisicao>;
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListarContasQueryKey();

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listarContas>>> = ({ signal }) =>
    listarContas({ signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listarContas>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListarContasQueryResult = NonNullable<Awaited<ReturnType<typeof listarContas>>>;
export type ListarContasQueryError = unknown;

export function useListarContas<TData = Awaited<ReturnType<typeof listarContas>>, TError = unknown>(
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarContas>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarContas>>,
          TError,
          Awaited<ReturnType<typeof listarContas>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarContas<TData = Awaited<ReturnType<typeof listarContas>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarContas>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarContas>>,
          TError,
          Awaited<ReturnType<typeof listarContas>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarContas<TData = Awaited<ReturnType<typeof listarContas>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarContas>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListarContas<TData = Awaited<ReturnType<typeof listarContas>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarContas>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListarContasQueryOptions(options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getCriarContasUrl = () => {
  return `/v1/contas`;
};

export const criarContas = async (
  novaContaDto: NovaContaDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<ContaDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<ContaDto>(getCriarContasUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(novaContaDto),
  });
};

export const getCriarContasMutationKey = () => ['criarContas'] as const;

export const getCriarContasMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof criarContas>>,
    TError,
    CriarContasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof criarContas>>,
  TError,
  CriarContasMutationVariables,
  TContext
> => {
  const mutationKey = getCriarContasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof criarContas>>,
    CriarContasMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return criarContas(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type CriarContasMutationResult = NonNullable<Awaited<ReturnType<typeof criarContas>>>;
export type CriarContasMutationBody = NovaContaDto;
export type CriarContasMutationError = unknown;
export type CriarContasMutationVariables = { data: NovaContaDto };

export const useCriarContas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof criarContas>>,
      TError,
      CriarContasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof criarContas>>,
  TError,
  CriarContasMutationVariables,
  TContext
> => {
  return useMutation(getCriarContasMutationOptions(options), queryClient);
};
export const getAtualizarContasUrl = (id: string) => {
  return `/v1/contas/${id}`;
};

export const atualizarContas = async (
  id: string,
  atualizacaoContaDto: AtualizacaoContaDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<ContaDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<ContaDto>(getAtualizarContasUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizacaoContaDto),
  });
};

export const getAtualizarContasMutationKey = () => ['atualizarContas'] as const;

export const getAtualizarContasMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarContas>>,
    TError,
    AtualizarContasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarContas>>,
  TError,
  AtualizarContasMutationVariables,
  TContext
> => {
  const mutationKey = getAtualizarContasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarContas>>,
    AtualizarContasMutationVariables
  > = (props) => {
    const { id, data } = props ?? {};

    return atualizarContas(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarContasMutationResult = NonNullable<
  Awaited<ReturnType<typeof atualizarContas>>
>;
export type AtualizarContasMutationBody = AtualizacaoContaDto;
export type AtualizarContasMutationError = unknown;
export type AtualizarContasMutationVariables = { id: string; data: AtualizacaoContaDto };

export const useAtualizarContas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarContas>>,
      TError,
      AtualizarContasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarContas>>,
  TError,
  AtualizarContasMutationVariables,
  TContext
> => {
  return useMutation(getAtualizarContasMutationOptions(options), queryClient);
};
export const getExcluirContasUrl = (id: string) => {
  return `/v1/contas/${id}`;
};

export const excluirContas = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  return requisicao<void>(getExcluirContasUrl(id), {
    ...options,
    method: 'DELETE',
  });
};

export const getExcluirContasMutationKey = () => ['excluirContas'] as const;

export const getExcluirContasMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof excluirContas>>,
    TError,
    ExcluirContasMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof excluirContas>>,
  TError,
  ExcluirContasMutationVariables,
  TContext
> => {
  const mutationKey = getExcluirContasMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof excluirContas>>,
    ExcluirContasMutationVariables
  > = (props) => {
    const { id } = props ?? {};

    return excluirContas(id, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExcluirContasMutationResult = NonNullable<Awaited<ReturnType<typeof excluirContas>>>;

export type ExcluirContasMutationError = unknown;
export type ExcluirContasMutationVariables = { id: string };

export const useExcluirContas = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof excluirContas>>,
      TError,
      ExcluirContasMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof excluirContas>>,
  TError,
  ExcluirContasMutationVariables,
  TContext
> => {
  return useMutation(getExcluirContasMutationOptions(options), queryClient);
};
