/**
 * Generated by orval 🍺
 * Do not edit manually.
 * API do Mony
 * API do app Monitorizze e da assistente Mony.
 * OpenAPI spec version: 1
 */
import { useMutation, useQuery } from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult,
} from '@tanstack/react-query';

import type {
  AtualizacaoTransacaoDto,
  ExcluirTransacoesParams,
  ListarTransacoesParams,
  LoteTransacoesDto,
  NovaTransacaoDto,
  PaginaTransacoesDto,
  RespostaTransacaoDto,
  ResultadoLoteDto,
  TotaisTransacoesDto,
  TotaisTransacoesParams,
  TransacaoDto,
} from '../modelos';

import { requisicao } from '../../requisicao';

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

const withQueryKey = <T extends object, K>(query: T, queryKey: K): T & { queryKey: K } => {
  const result = { queryKey } as T & { queryKey: K };
  for (const key of Object.keys(query)) {
    // The explicit queryKey always wins, matching the previous
    // `{ ...query, queryKey }` spread where it was set last.
    if (key === 'queryKey') continue;
    Object.defineProperty(result, key, {
      enumerable: true,
      configurable: true,
      get: () => (query as Record<string, unknown>)[key],
    });
  }
  return result;
};

export const getListarTransacoesUrl = (params?: ListarTransacoesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/v1/transacoes?${stringifiedParams}` : `/v1/transacoes`;
};

export const listarTransacoes = async (
  params?: ListarTransacoesParams,
  options?: Parameters<typeof requisicao>[1],
): Promise<PaginaTransacoesDto> => {
  return requisicao<PaginaTransacoesDto>(getListarTransacoesUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getListarTransacoesQueryKey = (params?: ListarTransacoesParams) => {
  return [`/v1/transacoes`, ...(params ? [params] : [])] as const;
};

export const getListarTransacoesQueryOptions = <
  TData = Awaited<ReturnType<typeof listarTransacoes>>,
  TError = unknown,
>(
  params?: ListarTransacoesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarTransacoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getListarTransacoesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof listarTransacoes>>> = ({ signal }) =>
    listarTransacoes(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof listarTransacoes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type ListarTransacoesQueryResult = NonNullable<Awaited<ReturnType<typeof listarTransacoes>>>;
export type ListarTransacoesQueryError = unknown;

export function useListarTransacoes<
  TData = Awaited<ReturnType<typeof listarTransacoes>>,
  TError = unknown,
>(
  params: undefined | ListarTransacoesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarTransacoes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarTransacoes>>,
          TError,
          Awaited<ReturnType<typeof listarTransacoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarTransacoes<
  TData = Awaited<ReturnType<typeof listarTransacoes>>,
  TError = unknown,
>(
  params?: ListarTransacoesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarTransacoes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listarTransacoes>>,
          TError,
          Awaited<ReturnType<typeof listarTransacoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useListarTransacoes<
  TData = Awaited<ReturnType<typeof listarTransacoes>>,
  TError = unknown,
>(
  params?: ListarTransacoesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarTransacoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useListarTransacoes<
  TData = Awaited<ReturnType<typeof listarTransacoes>>,
  TError = unknown,
>(
  params?: ListarTransacoesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof listarTransacoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getListarTransacoesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getRegistrarTransacoesUrl = () => {
  return `/v1/transacoes`;
};

export const registrarTransacoes = async (
  novaTransacaoDto: NovaTransacaoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<RespostaTransacaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<RespostaTransacaoDto>(getRegistrarTransacoesUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(novaTransacaoDto),
  });
};

export const getRegistrarTransacoesMutationKey = () => ['registrarTransacoes'] as const;

export const getRegistrarTransacoesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof registrarTransacoes>>,
    TError,
    RegistrarTransacoesMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof registrarTransacoes>>,
  TError,
  RegistrarTransacoesMutationVariables,
  TContext
> => {
  const mutationKey = getRegistrarTransacoesMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof registrarTransacoes>>,
    RegistrarTransacoesMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return registrarTransacoes(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type RegistrarTransacoesMutationResult = NonNullable<
  Awaited<ReturnType<typeof registrarTransacoes>>
>;
export type RegistrarTransacoesMutationBody = NovaTransacaoDto;
export type RegistrarTransacoesMutationError = unknown;
export type RegistrarTransacoesMutationVariables = { data: NovaTransacaoDto };

export const useRegistrarTransacoes = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof registrarTransacoes>>,
      TError,
      RegistrarTransacoesMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof registrarTransacoes>>,
  TError,
  RegistrarTransacoesMutationVariables,
  TContext
> => {
  return useMutation(getRegistrarTransacoesMutationOptions(options), queryClient);
};
export const getTotaisTransacoesUrl = (params?: TotaisTransacoesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/transacoes/totais?${stringifiedParams}`
    : `/v1/transacoes/totais`;
};

export const totaisTransacoes = async (
  params?: TotaisTransacoesParams,
  options?: Parameters<typeof requisicao>[1],
): Promise<TotaisTransacoesDto> => {
  return requisicao<TotaisTransacoesDto>(getTotaisTransacoesUrl(params), {
    ...options,
    method: 'GET',
  });
};

export const getTotaisTransacoesQueryKey = (params?: TotaisTransacoesParams) => {
  return [`/v1/transacoes/totais`, ...(params ? [params] : [])] as const;
};

export const getTotaisTransacoesQueryOptions = <
  TData = Awaited<ReturnType<typeof totaisTransacoes>>,
  TError = unknown,
>(
  params?: TotaisTransacoesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof totaisTransacoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getTotaisTransacoesQueryKey(params);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof totaisTransacoes>>> = ({ signal }) =>
    totaisTransacoes(params, { signal, ...requestOptions });

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof totaisTransacoes>>,
    TError,
    TData
  > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type TotaisTransacoesQueryResult = NonNullable<Awaited<ReturnType<typeof totaisTransacoes>>>;
export type TotaisTransacoesQueryError = unknown;

export function useTotaisTransacoes<
  TData = Awaited<ReturnType<typeof totaisTransacoes>>,
  TError = unknown,
>(
  params: undefined | TotaisTransacoesParams,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof totaisTransacoes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof totaisTransacoes>>,
          TError,
          Awaited<ReturnType<typeof totaisTransacoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTotaisTransacoes<
  TData = Awaited<ReturnType<typeof totaisTransacoes>>,
  TError = unknown,
>(
  params?: TotaisTransacoesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof totaisTransacoes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof totaisTransacoes>>,
          TError,
          Awaited<ReturnType<typeof totaisTransacoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useTotaisTransacoes<
  TData = Awaited<ReturnType<typeof totaisTransacoes>>,
  TError = unknown,
>(
  params?: TotaisTransacoesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof totaisTransacoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useTotaisTransacoes<
  TData = Awaited<ReturnType<typeof totaisTransacoes>>,
  TError = unknown,
>(
  params?: TotaisTransacoesParams,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof totaisTransacoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getTotaisTransacoesQueryOptions(params, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getBuscarTransacoesUrl = (id: string) => {
  return `/v1/transacoes/${id}`;
};

export const buscarTransacoes = async (
  id: string,
  options?: Parameters<typeof requisicao>[1],
): Promise<TransacaoDto> => {
  return requisicao<TransacaoDto>(getBuscarTransacoesUrl(id), {
    ...options,
    method: 'GET',
  });
};

export const getBuscarTransacoesQueryKey = (id: string) => {
  return [`/v1/transacoes/${id}`] as const;
};

export const getBuscarTransacoesQueryOptions = <
  TData = Awaited<ReturnType<typeof buscarTransacoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarTransacoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {};

  const queryKey = queryOptions?.queryKey ?? getBuscarTransacoesQueryKey(id);

  const queryFn: QueryFunction<Awaited<ReturnType<typeof buscarTransacoes>>> = ({ signal }) =>
    buscarTransacoes(id, { signal, ...requestOptions });

  return {
    queryKey,
    queryFn,
    enabled: id !== null && id !== undefined,
    ...queryOptions,
  } as UseQueryOptions<Awaited<ReturnType<typeof buscarTransacoes>>, TError, TData> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };
};

export type BuscarTransacoesQueryResult = NonNullable<Awaited<ReturnType<typeof buscarTransacoes>>>;
export type BuscarTransacoesQueryError = unknown;

export function useBuscarTransacoes<
  TData = Awaited<ReturnType<typeof buscarTransacoes>>,
  TError = unknown,
>(
  id: string,
  options: {
    query: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarTransacoes>>, TError, TData>> &
      Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTransacoes>>,
          TError,
          Awaited<ReturnType<typeof buscarTransacoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarTransacoes<
  TData = Awaited<ReturnType<typeof buscarTransacoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarTransacoes>>, TError, TData>> &
      Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof buscarTransacoes>>,
          TError,
          Awaited<ReturnType<typeof buscarTransacoes>>
        >,
        'initialData'
      >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
export function useBuscarTransacoes<
  TData = Awaited<ReturnType<typeof buscarTransacoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarTransacoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

export function useBuscarTransacoes<
  TData = Awaited<ReturnType<typeof buscarTransacoes>>,
  TError = unknown,
>(
  id: string,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof buscarTransacoes>>, TError, TData>>;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getBuscarTransacoesQueryOptions(id, options);

  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
  };

  return withQueryKey(query, queryOptions.queryKey);
}

export const getAtualizarTransacoesUrl = (id: string) => {
  return `/v1/transacoes/${id}`;
};

export const atualizarTransacoes = async (
  id: string,
  atualizacaoTransacaoDto: AtualizacaoTransacaoDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<RespostaTransacaoDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<RespostaTransacaoDto>(getAtualizarTransacoesUrl(id), {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(atualizacaoTransacaoDto),
  });
};

export const getAtualizarTransacoesMutationKey = () => ['atualizarTransacoes'] as const;

export const getAtualizarTransacoesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof atualizarTransacoes>>,
    TError,
    AtualizarTransacoesMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof atualizarTransacoes>>,
  TError,
  AtualizarTransacoesMutationVariables,
  TContext
> => {
  const mutationKey = getAtualizarTransacoesMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof atualizarTransacoes>>,
    AtualizarTransacoesMutationVariables
  > = (props) => {
    const { id, data } = props ?? {};

    return atualizarTransacoes(id, data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type AtualizarTransacoesMutationResult = NonNullable<
  Awaited<ReturnType<typeof atualizarTransacoes>>
>;
export type AtualizarTransacoesMutationBody = AtualizacaoTransacaoDto;
export type AtualizarTransacoesMutationError = unknown;
export type AtualizarTransacoesMutationVariables = { id: string; data: AtualizacaoTransacaoDto };

export const useAtualizarTransacoes = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof atualizarTransacoes>>,
      TError,
      AtualizarTransacoesMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof atualizarTransacoes>>,
  TError,
  AtualizarTransacoesMutationVariables,
  TContext
> => {
  return useMutation(getAtualizarTransacoesMutationOptions(options), queryClient);
};
export const getExcluirTransacoesUrl = (id: string, params?: ExcluirTransacoesParams) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {
    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value));
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0
    ? `/v1/transacoes/${id}?${stringifiedParams}`
    : `/v1/transacoes/${id}`;
};

export const excluirTransacoes = async (
  id: string,
  params?: ExcluirTransacoesParams,
  options?: Parameters<typeof requisicao>[1],
): Promise<void> => {
  return requisicao<void>(getExcluirTransacoesUrl(id, params), {
    ...options,
    method: 'DELETE',
  });
};

export const getExcluirTransacoesMutationKey = () => ['excluirTransacoes'] as const;

export const getExcluirTransacoesMutationOptions = <
  TError = unknown,
  TContext = unknown,
>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof excluirTransacoes>>,
    TError,
    ExcluirTransacoesMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof excluirTransacoes>>,
  TError,
  ExcluirTransacoesMutationVariables,
  TContext
> => {
  const mutationKey = getExcluirTransacoesMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof excluirTransacoes>>,
    ExcluirTransacoesMutationVariables
  > = (props) => {
    const { id, params } = props ?? {};

    return excluirTransacoes(id, params, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type ExcluirTransacoesMutationResult = NonNullable<
  Awaited<ReturnType<typeof excluirTransacoes>>
>;

export type ExcluirTransacoesMutationError = unknown;
export type ExcluirTransacoesMutationVariables = { id: string; params?: ExcluirTransacoesParams };

export const useExcluirTransacoes = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof excluirTransacoes>>,
      TError,
      ExcluirTransacoesMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof excluirTransacoes>>,
  TError,
  ExcluirTransacoesMutationVariables,
  TContext
> => {
  return useMutation(getExcluirTransacoesMutationOptions(options), queryClient);
};
export const getLoteTransacoesUrl = () => {
  return `/v1/transacoes/lote`;
};

export const loteTransacoes = async (
  loteTransacoesDto: LoteTransacoesDto,
  options?: Parameters<typeof requisicao>[1],
): Promise<ResultadoLoteDto> => {
  const getHeaders = (
    h?: NonNullable<RequestInit['headers']>,
  ): Record<string, string | readonly string[]> => {
    if (!h) return {};
    if (h instanceof Headers) return Object.fromEntries(h.entries());
    if (Symbol.iterator in h) {
      return Object.fromEntries(
        Array.from(
          h as Iterable<Iterable<string>>,
          (entry) => Array.from(entry) as [string, string],
        ),
      );
    }
    const headers: Record<string, string | readonly string[]> = {};
    for (const [name, value] of Object.entries<string | readonly string[] | undefined>(h)) {
      if (value !== undefined) headers[name] = value;
    }
    return headers;
  };
  return requisicao<ResultadoLoteDto>(getLoteTransacoesUrl(), {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...getHeaders(options?.headers) },
    body: JSON.stringify(loteTransacoesDto),
  });
};

export const getLoteTransacoesMutationKey = () => ['loteTransacoes'] as const;

export const getLoteTransacoesMutationOptions = <TError = unknown, TContext = unknown>(options?: {
  mutation?: UseMutationOptions<
    Awaited<ReturnType<typeof loteTransacoes>>,
    TError,
    LoteTransacoesMutationVariables,
    TContext
  >;
  request?: SecondParameter<typeof requisicao>;
}): UseMutationOptions<
  Awaited<ReturnType<typeof loteTransacoes>>,
  TError,
  LoteTransacoesMutationVariables,
  TContext
> => {
  const mutationKey = getLoteTransacoesMutationKey();
  const { mutation: mutationOptions, request: requestOptions } = options
    ? options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey
      ? options
      : { ...options, mutation: { ...options.mutation, mutationKey } }
    : { mutation: { mutationKey }, request: undefined };

  const mutationFn: MutationFunction<
    Awaited<ReturnType<typeof loteTransacoes>>,
    LoteTransacoesMutationVariables
  > = (props) => {
    const { data } = props ?? {};

    return loteTransacoes(data, requestOptions);
  };

  return { mutationFn, ...mutationOptions };
};

export type LoteTransacoesMutationResult = NonNullable<Awaited<ReturnType<typeof loteTransacoes>>>;
export type LoteTransacoesMutationBody = LoteTransacoesDto;
export type LoteTransacoesMutationError = unknown;
export type LoteTransacoesMutationVariables = { data: LoteTransacoesDto };

export const useLoteTransacoes = <TError = unknown, TContext = unknown>(
  options?: {
    mutation?: UseMutationOptions<
      Awaited<ReturnType<typeof loteTransacoes>>,
      TError,
      LoteTransacoesMutationVariables,
      TContext
    >;
    request?: SecondParameter<typeof requisicao>;
  },
  queryClient?: QueryClient,
): UseMutationResult<
  Awaited<ReturnType<typeof loteTransacoes>>,
  TError,
  LoteTransacoesMutationVariables,
  TContext
> => {
  return useMutation(getLoteTransacoesMutationOptions(options), queryClient);
};
